
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Album` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Album
 * 
 */
export type AlbumModel = runtime.Types.Result.DefaultSelection<Prisma.$AlbumPayload>

export type AggregateAlbum = {
  _count: AlbumCountAggregateOutputType | null
  _min: AlbumMinAggregateOutputType | null
  _max: AlbumMaxAggregateOutputType | null
}

export type AlbumMinAggregateOutputType = {
  id: string | null
  name: string | null
  artistId: string | null
  image: string | null
  songId: string | null
}

export type AlbumMaxAggregateOutputType = {
  id: string | null
  name: string | null
  artistId: string | null
  image: string | null
  songId: string | null
}

export type AlbumCountAggregateOutputType = {
  id: number
  name: number
  artistId: number
  image: number
  songId: number
  _all: number
}


export type AlbumMinAggregateInputType = {
  id?: true
  name?: true
  artistId?: true
  image?: true
  songId?: true
}

export type AlbumMaxAggregateInputType = {
  id?: true
  name?: true
  artistId?: true
  image?: true
  songId?: true
}

export type AlbumCountAggregateInputType = {
  id?: true
  name?: true
  artistId?: true
  image?: true
  songId?: true
  _all?: true
}

export type AlbumAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Album to aggregate.
   */
  where?: Prisma.AlbumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Albums to fetch.
   */
  orderBy?: Prisma.AlbumOrderByWithRelationInput | Prisma.AlbumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AlbumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Albums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Albums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Albums
  **/
  _count?: true | AlbumCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AlbumMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AlbumMaxAggregateInputType
}

export type GetAlbumAggregateType<T extends AlbumAggregateArgs> = {
      [P in keyof T & keyof AggregateAlbum]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAlbum[P]>
    : Prisma.GetScalarType<T[P], AggregateAlbum[P]>
}




export type AlbumGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AlbumWhereInput
  orderBy?: Prisma.AlbumOrderByWithAggregationInput | Prisma.AlbumOrderByWithAggregationInput[]
  by: Prisma.AlbumScalarFieldEnum[] | Prisma.AlbumScalarFieldEnum
  having?: Prisma.AlbumScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AlbumCountAggregateInputType | true
  _min?: AlbumMinAggregateInputType
  _max?: AlbumMaxAggregateInputType
}

export type AlbumGroupByOutputType = {
  id: string
  name: string
  artistId: string
  image: string
  songId: string
  _count: AlbumCountAggregateOutputType | null
  _min: AlbumMinAggregateOutputType | null
  _max: AlbumMaxAggregateOutputType | null
}

export type GetAlbumGroupByPayload<T extends AlbumGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AlbumGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AlbumGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AlbumGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AlbumGroupByOutputType[P]>
      }
    >
  >



export type AlbumWhereInput = {
  AND?: Prisma.AlbumWhereInput | Prisma.AlbumWhereInput[]
  OR?: Prisma.AlbumWhereInput[]
  NOT?: Prisma.AlbumWhereInput | Prisma.AlbumWhereInput[]
  id?: Prisma.StringFilter<"Album"> | string
  name?: Prisma.StringFilter<"Album"> | string
  artistId?: Prisma.StringFilter<"Album"> | string
  image?: Prisma.StringFilter<"Album"> | string
  songId?: Prisma.StringFilter<"Album"> | string
  artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
  songs?: Prisma.SongListRelationFilter
}

export type AlbumOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  artist?: Prisma.ArtistOrderByWithRelationInput
  songs?: Prisma.SongOrderByRelationAggregateInput
}

export type AlbumWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AlbumWhereInput | Prisma.AlbumWhereInput[]
  OR?: Prisma.AlbumWhereInput[]
  NOT?: Prisma.AlbumWhereInput | Prisma.AlbumWhereInput[]
  name?: Prisma.StringFilter<"Album"> | string
  artistId?: Prisma.StringFilter<"Album"> | string
  image?: Prisma.StringFilter<"Album"> | string
  songId?: Prisma.StringFilter<"Album"> | string
  artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
  songs?: Prisma.SongListRelationFilter
}, "id">

export type AlbumOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  _count?: Prisma.AlbumCountOrderByAggregateInput
  _max?: Prisma.AlbumMaxOrderByAggregateInput
  _min?: Prisma.AlbumMinOrderByAggregateInput
}

export type AlbumScalarWhereWithAggregatesInput = {
  AND?: Prisma.AlbumScalarWhereWithAggregatesInput | Prisma.AlbumScalarWhereWithAggregatesInput[]
  OR?: Prisma.AlbumScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AlbumScalarWhereWithAggregatesInput | Prisma.AlbumScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Album"> | string
  name?: Prisma.StringWithAggregatesFilter<"Album"> | string
  artistId?: Prisma.StringWithAggregatesFilter<"Album"> | string
  image?: Prisma.StringWithAggregatesFilter<"Album"> | string
  songId?: Prisma.StringWithAggregatesFilter<"Album"> | string
}

export type AlbumCreateInput = {
  id?: string
  name: string
  image: string
  songId: string
  artist: Prisma.ArtistCreateNestedOneWithoutAlbumsInput
  songs?: Prisma.SongCreateNestedManyWithoutAlbumInput
}

export type AlbumUncheckedCreateInput = {
  id?: string
  name: string
  artistId: string
  image: string
  songId: string
  songs?: Prisma.SongUncheckedCreateNestedManyWithoutAlbumInput
}

export type AlbumUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.ArtistUpdateOneRequiredWithoutAlbumsNestedInput
  songs?: Prisma.SongUpdateManyWithoutAlbumNestedInput
}

export type AlbumUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  artistId?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  songs?: Prisma.SongUncheckedUpdateManyWithoutAlbumNestedInput
}

export type AlbumCreateManyInput = {
  id?: string
  name: string
  artistId: string
  image: string
  songId: string
}

export type AlbumUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AlbumUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  artistId?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AlbumNullableScalarRelationFilter = {
  is?: Prisma.AlbumWhereInput | null
  isNot?: Prisma.AlbumWhereInput | null
}

export type AlbumListRelationFilter = {
  every?: Prisma.AlbumWhereInput
  some?: Prisma.AlbumWhereInput
  none?: Prisma.AlbumWhereInput
}

export type AlbumOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AlbumCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  songId?: Prisma.SortOrder
}

export type AlbumMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  songId?: Prisma.SortOrder
}

export type AlbumMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  songId?: Prisma.SortOrder
}

export type AlbumCreateNestedOneWithoutSongsInput = {
  create?: Prisma.XOR<Prisma.AlbumCreateWithoutSongsInput, Prisma.AlbumUncheckedCreateWithoutSongsInput>
  connectOrCreate?: Prisma.AlbumCreateOrConnectWithoutSongsInput
  connect?: Prisma.AlbumWhereUniqueInput
}

export type AlbumUpdateOneWithoutSongsNestedInput = {
  create?: Prisma.XOR<Prisma.AlbumCreateWithoutSongsInput, Prisma.AlbumUncheckedCreateWithoutSongsInput>
  connectOrCreate?: Prisma.AlbumCreateOrConnectWithoutSongsInput
  upsert?: Prisma.AlbumUpsertWithoutSongsInput
  disconnect?: Prisma.AlbumWhereInput | boolean
  delete?: Prisma.AlbumWhereInput | boolean
  connect?: Prisma.AlbumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AlbumUpdateToOneWithWhereWithoutSongsInput, Prisma.AlbumUpdateWithoutSongsInput>, Prisma.AlbumUncheckedUpdateWithoutSongsInput>
}

export type AlbumCreateNestedManyWithoutArtistInput = {
  create?: Prisma.XOR<Prisma.AlbumCreateWithoutArtistInput, Prisma.AlbumUncheckedCreateWithoutArtistInput> | Prisma.AlbumCreateWithoutArtistInput[] | Prisma.AlbumUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.AlbumCreateOrConnectWithoutArtistInput | Prisma.AlbumCreateOrConnectWithoutArtistInput[]
  createMany?: Prisma.AlbumCreateManyArtistInputEnvelope
  connect?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
}

export type AlbumUncheckedCreateNestedManyWithoutArtistInput = {
  create?: Prisma.XOR<Prisma.AlbumCreateWithoutArtistInput, Prisma.AlbumUncheckedCreateWithoutArtistInput> | Prisma.AlbumCreateWithoutArtistInput[] | Prisma.AlbumUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.AlbumCreateOrConnectWithoutArtistInput | Prisma.AlbumCreateOrConnectWithoutArtistInput[]
  createMany?: Prisma.AlbumCreateManyArtistInputEnvelope
  connect?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
}

export type AlbumUpdateManyWithoutArtistNestedInput = {
  create?: Prisma.XOR<Prisma.AlbumCreateWithoutArtistInput, Prisma.AlbumUncheckedCreateWithoutArtistInput> | Prisma.AlbumCreateWithoutArtistInput[] | Prisma.AlbumUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.AlbumCreateOrConnectWithoutArtistInput | Prisma.AlbumCreateOrConnectWithoutArtistInput[]
  upsert?: Prisma.AlbumUpsertWithWhereUniqueWithoutArtistInput | Prisma.AlbumUpsertWithWhereUniqueWithoutArtistInput[]
  createMany?: Prisma.AlbumCreateManyArtistInputEnvelope
  set?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  disconnect?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  delete?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  connect?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  update?: Prisma.AlbumUpdateWithWhereUniqueWithoutArtistInput | Prisma.AlbumUpdateWithWhereUniqueWithoutArtistInput[]
  updateMany?: Prisma.AlbumUpdateManyWithWhereWithoutArtistInput | Prisma.AlbumUpdateManyWithWhereWithoutArtistInput[]
  deleteMany?: Prisma.AlbumScalarWhereInput | Prisma.AlbumScalarWhereInput[]
}

export type AlbumUncheckedUpdateManyWithoutArtistNestedInput = {
  create?: Prisma.XOR<Prisma.AlbumCreateWithoutArtistInput, Prisma.AlbumUncheckedCreateWithoutArtistInput> | Prisma.AlbumCreateWithoutArtistInput[] | Prisma.AlbumUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.AlbumCreateOrConnectWithoutArtistInput | Prisma.AlbumCreateOrConnectWithoutArtistInput[]
  upsert?: Prisma.AlbumUpsertWithWhereUniqueWithoutArtistInput | Prisma.AlbumUpsertWithWhereUniqueWithoutArtistInput[]
  createMany?: Prisma.AlbumCreateManyArtistInputEnvelope
  set?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  disconnect?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  delete?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  connect?: Prisma.AlbumWhereUniqueInput | Prisma.AlbumWhereUniqueInput[]
  update?: Prisma.AlbumUpdateWithWhereUniqueWithoutArtistInput | Prisma.AlbumUpdateWithWhereUniqueWithoutArtistInput[]
  updateMany?: Prisma.AlbumUpdateManyWithWhereWithoutArtistInput | Prisma.AlbumUpdateManyWithWhereWithoutArtistInput[]
  deleteMany?: Prisma.AlbumScalarWhereInput | Prisma.AlbumScalarWhereInput[]
}

export type AlbumCreateWithoutSongsInput = {
  id?: string
  name: string
  image: string
  songId: string
  artist: Prisma.ArtistCreateNestedOneWithoutAlbumsInput
}

export type AlbumUncheckedCreateWithoutSongsInput = {
  id?: string
  name: string
  artistId: string
  image: string
  songId: string
}

export type AlbumCreateOrConnectWithoutSongsInput = {
  where: Prisma.AlbumWhereUniqueInput
  create: Prisma.XOR<Prisma.AlbumCreateWithoutSongsInput, Prisma.AlbumUncheckedCreateWithoutSongsInput>
}

export type AlbumUpsertWithoutSongsInput = {
  update: Prisma.XOR<Prisma.AlbumUpdateWithoutSongsInput, Prisma.AlbumUncheckedUpdateWithoutSongsInput>
  create: Prisma.XOR<Prisma.AlbumCreateWithoutSongsInput, Prisma.AlbumUncheckedCreateWithoutSongsInput>
  where?: Prisma.AlbumWhereInput
}

export type AlbumUpdateToOneWithWhereWithoutSongsInput = {
  where?: Prisma.AlbumWhereInput
  data: Prisma.XOR<Prisma.AlbumUpdateWithoutSongsInput, Prisma.AlbumUncheckedUpdateWithoutSongsInput>
}

export type AlbumUpdateWithoutSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.ArtistUpdateOneRequiredWithoutAlbumsNestedInput
}

export type AlbumUncheckedUpdateWithoutSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  artistId?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AlbumCreateWithoutArtistInput = {
  id?: string
  name: string
  image: string
  songId: string
  songs?: Prisma.SongCreateNestedManyWithoutAlbumInput
}

export type AlbumUncheckedCreateWithoutArtistInput = {
  id?: string
  name: string
  image: string
  songId: string
  songs?: Prisma.SongUncheckedCreateNestedManyWithoutAlbumInput
}

export type AlbumCreateOrConnectWithoutArtistInput = {
  where: Prisma.AlbumWhereUniqueInput
  create: Prisma.XOR<Prisma.AlbumCreateWithoutArtistInput, Prisma.AlbumUncheckedCreateWithoutArtistInput>
}

export type AlbumCreateManyArtistInputEnvelope = {
  data: Prisma.AlbumCreateManyArtistInput | Prisma.AlbumCreateManyArtistInput[]
  skipDuplicates?: boolean
}

export type AlbumUpsertWithWhereUniqueWithoutArtistInput = {
  where: Prisma.AlbumWhereUniqueInput
  update: Prisma.XOR<Prisma.AlbumUpdateWithoutArtistInput, Prisma.AlbumUncheckedUpdateWithoutArtistInput>
  create: Prisma.XOR<Prisma.AlbumCreateWithoutArtistInput, Prisma.AlbumUncheckedCreateWithoutArtistInput>
}

export type AlbumUpdateWithWhereUniqueWithoutArtistInput = {
  where: Prisma.AlbumWhereUniqueInput
  data: Prisma.XOR<Prisma.AlbumUpdateWithoutArtistInput, Prisma.AlbumUncheckedUpdateWithoutArtistInput>
}

export type AlbumUpdateManyWithWhereWithoutArtistInput = {
  where: Prisma.AlbumScalarWhereInput
  data: Prisma.XOR<Prisma.AlbumUpdateManyMutationInput, Prisma.AlbumUncheckedUpdateManyWithoutArtistInput>
}

export type AlbumScalarWhereInput = {
  AND?: Prisma.AlbumScalarWhereInput | Prisma.AlbumScalarWhereInput[]
  OR?: Prisma.AlbumScalarWhereInput[]
  NOT?: Prisma.AlbumScalarWhereInput | Prisma.AlbumScalarWhereInput[]
  id?: Prisma.StringFilter<"Album"> | string
  name?: Prisma.StringFilter<"Album"> | string
  artistId?: Prisma.StringFilter<"Album"> | string
  image?: Prisma.StringFilter<"Album"> | string
  songId?: Prisma.StringFilter<"Album"> | string
}

export type AlbumCreateManyArtistInput = {
  id?: string
  name: string
  image: string
  songId: string
}

export type AlbumUpdateWithoutArtistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  songs?: Prisma.SongUpdateManyWithoutAlbumNestedInput
}

export type AlbumUncheckedUpdateWithoutArtistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  songs?: Prisma.SongUncheckedUpdateManyWithoutAlbumNestedInput
}

export type AlbumUncheckedUpdateManyWithoutArtistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type AlbumCountOutputType
 */

export type AlbumCountOutputType = {
  songs: number
}

export type AlbumCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  songs?: boolean | AlbumCountOutputTypeCountSongsArgs
}

/**
 * AlbumCountOutputType without action
 */
export type AlbumCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AlbumCountOutputType
   */
  select?: Prisma.AlbumCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AlbumCountOutputType without action
 */
export type AlbumCountOutputTypeCountSongsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SongWhereInput
}


export type AlbumSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  artistId?: boolean
  image?: boolean
  songId?: boolean
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
  songs?: boolean | Prisma.Album$songsArgs<ExtArgs>
  _count?: boolean | Prisma.AlbumCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["album"]>

export type AlbumSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  artistId?: boolean
  image?: boolean
  songId?: boolean
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["album"]>

export type AlbumSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  artistId?: boolean
  image?: boolean
  songId?: boolean
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["album"]>

export type AlbumSelectScalar = {
  id?: boolean
  name?: boolean
  artistId?: boolean
  image?: boolean
  songId?: boolean
}

export type AlbumOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "artistId" | "image" | "songId", ExtArgs["result"]["album"]>
export type AlbumInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
  songs?: boolean | Prisma.Album$songsArgs<ExtArgs>
  _count?: boolean | Prisma.AlbumCountOutputTypeDefaultArgs<ExtArgs>
}
export type AlbumIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}
export type AlbumIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}

export type $AlbumPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Album"
  objects: {
    artist: Prisma.$ArtistPayload<ExtArgs>
    songs: Prisma.$SongPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    artistId: string
    image: string
    songId: string
  }, ExtArgs["result"]["album"]>
  composites: {}
}

export type AlbumGetPayload<S extends boolean | null | undefined | AlbumDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AlbumPayload, S>

export type AlbumCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AlbumFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AlbumCountAggregateInputType | true
  }

export interface AlbumDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Album'], meta: { name: 'Album' } }
  /**
   * Find zero or one Album that matches the filter.
   * @param {AlbumFindUniqueArgs} args - Arguments to find a Album
   * @example
   * // Get one Album
   * const album = await prisma.album.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AlbumFindUniqueArgs>(args: Prisma.SelectSubset<T, AlbumFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Album that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AlbumFindUniqueOrThrowArgs} args - Arguments to find a Album
   * @example
   * // Get one Album
   * const album = await prisma.album.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AlbumFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AlbumFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Album that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlbumFindFirstArgs} args - Arguments to find a Album
   * @example
   * // Get one Album
   * const album = await prisma.album.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AlbumFindFirstArgs>(args?: Prisma.SelectSubset<T, AlbumFindFirstArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Album that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlbumFindFirstOrThrowArgs} args - Arguments to find a Album
   * @example
   * // Get one Album
   * const album = await prisma.album.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AlbumFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AlbumFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Albums that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlbumFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Albums
   * const albums = await prisma.album.findMany()
   * 
   * // Get first 10 Albums
   * const albums = await prisma.album.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const albumWithIdOnly = await prisma.album.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AlbumFindManyArgs>(args?: Prisma.SelectSubset<T, AlbumFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Album.
   * @param {AlbumCreateArgs} args - Arguments to create a Album.
   * @example
   * // Create one Album
   * const Album = await prisma.album.create({
   *   data: {
   *     // ... data to create a Album
   *   }
   * })
   * 
   */
  create<T extends AlbumCreateArgs>(args: Prisma.SelectSubset<T, AlbumCreateArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Albums.
   * @param {AlbumCreateManyArgs} args - Arguments to create many Albums.
   * @example
   * // Create many Albums
   * const album = await prisma.album.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AlbumCreateManyArgs>(args?: Prisma.SelectSubset<T, AlbumCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Albums and returns the data saved in the database.
   * @param {AlbumCreateManyAndReturnArgs} args - Arguments to create many Albums.
   * @example
   * // Create many Albums
   * const album = await prisma.album.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Albums and only return the `id`
   * const albumWithIdOnly = await prisma.album.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AlbumCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AlbumCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Album.
   * @param {AlbumDeleteArgs} args - Arguments to delete one Album.
   * @example
   * // Delete one Album
   * const Album = await prisma.album.delete({
   *   where: {
   *     // ... filter to delete one Album
   *   }
   * })
   * 
   */
  delete<T extends AlbumDeleteArgs>(args: Prisma.SelectSubset<T, AlbumDeleteArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Album.
   * @param {AlbumUpdateArgs} args - Arguments to update one Album.
   * @example
   * // Update one Album
   * const album = await prisma.album.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AlbumUpdateArgs>(args: Prisma.SelectSubset<T, AlbumUpdateArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Albums.
   * @param {AlbumDeleteManyArgs} args - Arguments to filter Albums to delete.
   * @example
   * // Delete a few Albums
   * const { count } = await prisma.album.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AlbumDeleteManyArgs>(args?: Prisma.SelectSubset<T, AlbumDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Albums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlbumUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Albums
   * const album = await prisma.album.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AlbumUpdateManyArgs>(args: Prisma.SelectSubset<T, AlbumUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Albums and returns the data updated in the database.
   * @param {AlbumUpdateManyAndReturnArgs} args - Arguments to update many Albums.
   * @example
   * // Update many Albums
   * const album = await prisma.album.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Albums and only return the `id`
   * const albumWithIdOnly = await prisma.album.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AlbumUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AlbumUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Album.
   * @param {AlbumUpsertArgs} args - Arguments to update or create a Album.
   * @example
   * // Update or create a Album
   * const album = await prisma.album.upsert({
   *   create: {
   *     // ... data to create a Album
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Album we want to update
   *   }
   * })
   */
  upsert<T extends AlbumUpsertArgs>(args: Prisma.SelectSubset<T, AlbumUpsertArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Albums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlbumCountArgs} args - Arguments to filter Albums to count.
   * @example
   * // Count the number of Albums
   * const count = await prisma.album.count({
   *   where: {
   *     // ... the filter for the Albums we want to count
   *   }
   * })
  **/
  count<T extends AlbumCountArgs>(
    args?: Prisma.Subset<T, AlbumCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AlbumCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Album.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlbumAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AlbumAggregateArgs>(args: Prisma.Subset<T, AlbumAggregateArgs>): Prisma.PrismaPromise<GetAlbumAggregateType<T>>

  /**
   * Group by Album.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AlbumGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AlbumGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AlbumGroupByArgs['orderBy'] }
      : { orderBy?: AlbumGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AlbumGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAlbumGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Album model
 */
readonly fields: AlbumFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Album.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AlbumClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  artist<T extends Prisma.ArtistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ArtistDefaultArgs<ExtArgs>>): Prisma.Prisma__ArtistClient<runtime.Types.Result.GetResult<Prisma.$ArtistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  songs<T extends Prisma.Album$songsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Album$songsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Album model
 */
export interface AlbumFieldRefs {
  readonly id: Prisma.FieldRef<"Album", 'String'>
  readonly name: Prisma.FieldRef<"Album", 'String'>
  readonly artistId: Prisma.FieldRef<"Album", 'String'>
  readonly image: Prisma.FieldRef<"Album", 'String'>
  readonly songId: Prisma.FieldRef<"Album", 'String'>
}
    

// Custom InputTypes
/**
 * Album findUnique
 */
export type AlbumFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * Filter, which Album to fetch.
   */
  where: Prisma.AlbumWhereUniqueInput
}

/**
 * Album findUniqueOrThrow
 */
export type AlbumFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * Filter, which Album to fetch.
   */
  where: Prisma.AlbumWhereUniqueInput
}

/**
 * Album findFirst
 */
export type AlbumFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * Filter, which Album to fetch.
   */
  where?: Prisma.AlbumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Albums to fetch.
   */
  orderBy?: Prisma.AlbumOrderByWithRelationInput | Prisma.AlbumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Albums.
   */
  cursor?: Prisma.AlbumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Albums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Albums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Albums.
   */
  distinct?: Prisma.AlbumScalarFieldEnum | Prisma.AlbumScalarFieldEnum[]
}

/**
 * Album findFirstOrThrow
 */
export type AlbumFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * Filter, which Album to fetch.
   */
  where?: Prisma.AlbumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Albums to fetch.
   */
  orderBy?: Prisma.AlbumOrderByWithRelationInput | Prisma.AlbumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Albums.
   */
  cursor?: Prisma.AlbumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Albums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Albums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Albums.
   */
  distinct?: Prisma.AlbumScalarFieldEnum | Prisma.AlbumScalarFieldEnum[]
}

/**
 * Album findMany
 */
export type AlbumFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * Filter, which Albums to fetch.
   */
  where?: Prisma.AlbumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Albums to fetch.
   */
  orderBy?: Prisma.AlbumOrderByWithRelationInput | Prisma.AlbumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Albums.
   */
  cursor?: Prisma.AlbumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Albums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Albums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Albums.
   */
  distinct?: Prisma.AlbumScalarFieldEnum | Prisma.AlbumScalarFieldEnum[]
}

/**
 * Album create
 */
export type AlbumCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * The data needed to create a Album.
   */
  data: Prisma.XOR<Prisma.AlbumCreateInput, Prisma.AlbumUncheckedCreateInput>
}

/**
 * Album createMany
 */
export type AlbumCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Albums.
   */
  data: Prisma.AlbumCreateManyInput | Prisma.AlbumCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Album createManyAndReturn
 */
export type AlbumCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * The data used to create many Albums.
   */
  data: Prisma.AlbumCreateManyInput | Prisma.AlbumCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Album update
 */
export type AlbumUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * The data needed to update a Album.
   */
  data: Prisma.XOR<Prisma.AlbumUpdateInput, Prisma.AlbumUncheckedUpdateInput>
  /**
   * Choose, which Album to update.
   */
  where: Prisma.AlbumWhereUniqueInput
}

/**
 * Album updateMany
 */
export type AlbumUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Albums.
   */
  data: Prisma.XOR<Prisma.AlbumUpdateManyMutationInput, Prisma.AlbumUncheckedUpdateManyInput>
  /**
   * Filter which Albums to update
   */
  where?: Prisma.AlbumWhereInput
  /**
   * Limit how many Albums to update.
   */
  limit?: number
}

/**
 * Album updateManyAndReturn
 */
export type AlbumUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * The data used to update Albums.
   */
  data: Prisma.XOR<Prisma.AlbumUpdateManyMutationInput, Prisma.AlbumUncheckedUpdateManyInput>
  /**
   * Filter which Albums to update
   */
  where?: Prisma.AlbumWhereInput
  /**
   * Limit how many Albums to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Album upsert
 */
export type AlbumUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * The filter to search for the Album to update in case it exists.
   */
  where: Prisma.AlbumWhereUniqueInput
  /**
   * In case the Album found by the `where` argument doesn't exist, create a new Album with this data.
   */
  create: Prisma.XOR<Prisma.AlbumCreateInput, Prisma.AlbumUncheckedCreateInput>
  /**
   * In case the Album was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AlbumUpdateInput, Prisma.AlbumUncheckedUpdateInput>
}

/**
 * Album delete
 */
export type AlbumDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  /**
   * Filter which Album to delete.
   */
  where: Prisma.AlbumWhereUniqueInput
}

/**
 * Album deleteMany
 */
export type AlbumDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Albums to delete
   */
  where?: Prisma.AlbumWhereInput
  /**
   * Limit how many Albums to delete.
   */
  limit?: number
}

/**
 * Album.songs
 */
export type Album$songsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  where?: Prisma.SongWhereInput
  orderBy?: Prisma.SongOrderByWithRelationInput | Prisma.SongOrderByWithRelationInput[]
  cursor?: Prisma.SongWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SongScalarFieldEnum | Prisma.SongScalarFieldEnum[]
}

/**
 * Album without action
 */
export type AlbumDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
}
