
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlaylistSong` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PlaylistSong
 * 
 */
export type PlaylistSongModel = runtime.Types.Result.DefaultSelection<Prisma.$PlaylistSongPayload>

export type AggregatePlaylistSong = {
  _count: PlaylistSongCountAggregateOutputType | null
  _avg: PlaylistSongAvgAggregateOutputType | null
  _sum: PlaylistSongSumAggregateOutputType | null
  _min: PlaylistSongMinAggregateOutputType | null
  _max: PlaylistSongMaxAggregateOutputType | null
}

export type PlaylistSongAvgAggregateOutputType = {
  position: number | null
}

export type PlaylistSongSumAggregateOutputType = {
  position: number | null
}

export type PlaylistSongMinAggregateOutputType = {
  id: string | null
  playlistId: string | null
  songId: string | null
  position: number | null
}

export type PlaylistSongMaxAggregateOutputType = {
  id: string | null
  playlistId: string | null
  songId: string | null
  position: number | null
}

export type PlaylistSongCountAggregateOutputType = {
  id: number
  playlistId: number
  songId: number
  position: number
  _all: number
}


export type PlaylistSongAvgAggregateInputType = {
  position?: true
}

export type PlaylistSongSumAggregateInputType = {
  position?: true
}

export type PlaylistSongMinAggregateInputType = {
  id?: true
  playlistId?: true
  songId?: true
  position?: true
}

export type PlaylistSongMaxAggregateInputType = {
  id?: true
  playlistId?: true
  songId?: true
  position?: true
}

export type PlaylistSongCountAggregateInputType = {
  id?: true
  playlistId?: true
  songId?: true
  position?: true
  _all?: true
}

export type PlaylistSongAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaylistSong to aggregate.
   */
  where?: Prisma.PlaylistSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistSongs to fetch.
   */
  orderBy?: Prisma.PlaylistSongOrderByWithRelationInput | Prisma.PlaylistSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaylistSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlaylistSongs
  **/
  _count?: true | PlaylistSongCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlaylistSongAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlaylistSongSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaylistSongMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaylistSongMaxAggregateInputType
}

export type GetPlaylistSongAggregateType<T extends PlaylistSongAggregateArgs> = {
      [P in keyof T & keyof AggregatePlaylistSong]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlaylistSong[P]>
    : Prisma.GetScalarType<T[P], AggregatePlaylistSong[P]>
}




export type PlaylistSongGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaylistSongWhereInput
  orderBy?: Prisma.PlaylistSongOrderByWithAggregationInput | Prisma.PlaylistSongOrderByWithAggregationInput[]
  by: Prisma.PlaylistSongScalarFieldEnum[] | Prisma.PlaylistSongScalarFieldEnum
  having?: Prisma.PlaylistSongScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaylistSongCountAggregateInputType | true
  _avg?: PlaylistSongAvgAggregateInputType
  _sum?: PlaylistSongSumAggregateInputType
  _min?: PlaylistSongMinAggregateInputType
  _max?: PlaylistSongMaxAggregateInputType
}

export type PlaylistSongGroupByOutputType = {
  id: string
  playlistId: string
  songId: string
  position: number
  _count: PlaylistSongCountAggregateOutputType | null
  _avg: PlaylistSongAvgAggregateOutputType | null
  _sum: PlaylistSongSumAggregateOutputType | null
  _min: PlaylistSongMinAggregateOutputType | null
  _max: PlaylistSongMaxAggregateOutputType | null
}

export type GetPlaylistSongGroupByPayload<T extends PlaylistSongGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaylistSongGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaylistSongGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaylistSongGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaylistSongGroupByOutputType[P]>
      }
    >
  >



export type PlaylistSongWhereInput = {
  AND?: Prisma.PlaylistSongWhereInput | Prisma.PlaylistSongWhereInput[]
  OR?: Prisma.PlaylistSongWhereInput[]
  NOT?: Prisma.PlaylistSongWhereInput | Prisma.PlaylistSongWhereInput[]
  id?: Prisma.StringFilter<"PlaylistSong"> | string
  playlistId?: Prisma.StringFilter<"PlaylistSong"> | string
  songId?: Prisma.StringFilter<"PlaylistSong"> | string
  position?: Prisma.IntFilter<"PlaylistSong"> | number
  playlist?: Prisma.XOR<Prisma.PlaylistScalarRelationFilter, Prisma.PlaylistWhereInput>
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
}

export type PlaylistSongOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  playlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  playlist?: Prisma.PlaylistOrderByWithRelationInput
  song?: Prisma.SongOrderByWithRelationInput
}

export type PlaylistSongWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PlaylistSongWhereInput | Prisma.PlaylistSongWhereInput[]
  OR?: Prisma.PlaylistSongWhereInput[]
  NOT?: Prisma.PlaylistSongWhereInput | Prisma.PlaylistSongWhereInput[]
  playlistId?: Prisma.StringFilter<"PlaylistSong"> | string
  songId?: Prisma.StringFilter<"PlaylistSong"> | string
  position?: Prisma.IntFilter<"PlaylistSong"> | number
  playlist?: Prisma.XOR<Prisma.PlaylistScalarRelationFilter, Prisma.PlaylistWhereInput>
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
}, "id">

export type PlaylistSongOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  playlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  _count?: Prisma.PlaylistSongCountOrderByAggregateInput
  _avg?: Prisma.PlaylistSongAvgOrderByAggregateInput
  _max?: Prisma.PlaylistSongMaxOrderByAggregateInput
  _min?: Prisma.PlaylistSongMinOrderByAggregateInput
  _sum?: Prisma.PlaylistSongSumOrderByAggregateInput
}

export type PlaylistSongScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaylistSongScalarWhereWithAggregatesInput | Prisma.PlaylistSongScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaylistSongScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaylistSongScalarWhereWithAggregatesInput | Prisma.PlaylistSongScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PlaylistSong"> | string
  playlistId?: Prisma.StringWithAggregatesFilter<"PlaylistSong"> | string
  songId?: Prisma.StringWithAggregatesFilter<"PlaylistSong"> | string
  position?: Prisma.IntWithAggregatesFilter<"PlaylistSong"> | number
}

export type PlaylistSongCreateInput = {
  id?: string
  position: number
  playlist: Prisma.PlaylistCreateNestedOneWithoutSongsInput
  song: Prisma.SongCreateNestedOneWithoutPlaylistSongsInput
}

export type PlaylistSongUncheckedCreateInput = {
  id?: string
  playlistId: string
  songId: string
  position: number
}

export type PlaylistSongUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  playlist?: Prisma.PlaylistUpdateOneRequiredWithoutSongsNestedInput
  song?: Prisma.SongUpdateOneRequiredWithoutPlaylistSongsNestedInput
}

export type PlaylistSongUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaylistSongCreateManyInput = {
  id?: string
  playlistId: string
  songId: string
  position: number
}

export type PlaylistSongUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaylistSongUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaylistSongListRelationFilter = {
  every?: Prisma.PlaylistSongWhereInput
  some?: Prisma.PlaylistSongWhereInput
  none?: Prisma.PlaylistSongWhereInput
}

export type PlaylistSongOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PlaylistSongCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type PlaylistSongAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type PlaylistSongMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type PlaylistSongMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playlistId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type PlaylistSongSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type PlaylistSongCreateNestedManyWithoutPlaylistInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistSongCreateWithoutPlaylistInput[] | Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistSongCreateManyPlaylistInputEnvelope
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
}

export type PlaylistSongUncheckedCreateNestedManyWithoutPlaylistInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistSongCreateWithoutPlaylistInput[] | Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistSongCreateManyPlaylistInputEnvelope
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
}

export type PlaylistSongUpdateManyWithoutPlaylistNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistSongCreateWithoutPlaylistInput[] | Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput[]
  upsert?: Prisma.PlaylistSongUpsertWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistSongUpsertWithWhereUniqueWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistSongCreateManyPlaylistInputEnvelope
  set?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  disconnect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  delete?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  update?: Prisma.PlaylistSongUpdateWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistSongUpdateWithWhereUniqueWithoutPlaylistInput[]
  updateMany?: Prisma.PlaylistSongUpdateManyWithWhereWithoutPlaylistInput | Prisma.PlaylistSongUpdateManyWithWhereWithoutPlaylistInput[]
  deleteMany?: Prisma.PlaylistSongScalarWhereInput | Prisma.PlaylistSongScalarWhereInput[]
}

export type PlaylistSongUncheckedUpdateManyWithoutPlaylistNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput> | Prisma.PlaylistSongCreateWithoutPlaylistInput[] | Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput | Prisma.PlaylistSongCreateOrConnectWithoutPlaylistInput[]
  upsert?: Prisma.PlaylistSongUpsertWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistSongUpsertWithWhereUniqueWithoutPlaylistInput[]
  createMany?: Prisma.PlaylistSongCreateManyPlaylistInputEnvelope
  set?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  disconnect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  delete?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  update?: Prisma.PlaylistSongUpdateWithWhereUniqueWithoutPlaylistInput | Prisma.PlaylistSongUpdateWithWhereUniqueWithoutPlaylistInput[]
  updateMany?: Prisma.PlaylistSongUpdateManyWithWhereWithoutPlaylistInput | Prisma.PlaylistSongUpdateManyWithWhereWithoutPlaylistInput[]
  deleteMany?: Prisma.PlaylistSongScalarWhereInput | Prisma.PlaylistSongScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PlaylistSongCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutSongInput, Prisma.PlaylistSongUncheckedCreateWithoutSongInput> | Prisma.PlaylistSongCreateWithoutSongInput[] | Prisma.PlaylistSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutSongInput | Prisma.PlaylistSongCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.PlaylistSongCreateManySongInputEnvelope
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
}

export type PlaylistSongUncheckedCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutSongInput, Prisma.PlaylistSongUncheckedCreateWithoutSongInput> | Prisma.PlaylistSongCreateWithoutSongInput[] | Prisma.PlaylistSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutSongInput | Prisma.PlaylistSongCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.PlaylistSongCreateManySongInputEnvelope
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
}

export type PlaylistSongUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutSongInput, Prisma.PlaylistSongUncheckedCreateWithoutSongInput> | Prisma.PlaylistSongCreateWithoutSongInput[] | Prisma.PlaylistSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutSongInput | Prisma.PlaylistSongCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.PlaylistSongUpsertWithWhereUniqueWithoutSongInput | Prisma.PlaylistSongUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.PlaylistSongCreateManySongInputEnvelope
  set?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  disconnect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  delete?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  update?: Prisma.PlaylistSongUpdateWithWhereUniqueWithoutSongInput | Prisma.PlaylistSongUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.PlaylistSongUpdateManyWithWhereWithoutSongInput | Prisma.PlaylistSongUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.PlaylistSongScalarWhereInput | Prisma.PlaylistSongScalarWhereInput[]
}

export type PlaylistSongUncheckedUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.PlaylistSongCreateWithoutSongInput, Prisma.PlaylistSongUncheckedCreateWithoutSongInput> | Prisma.PlaylistSongCreateWithoutSongInput[] | Prisma.PlaylistSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.PlaylistSongCreateOrConnectWithoutSongInput | Prisma.PlaylistSongCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.PlaylistSongUpsertWithWhereUniqueWithoutSongInput | Prisma.PlaylistSongUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.PlaylistSongCreateManySongInputEnvelope
  set?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  disconnect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  delete?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  connect?: Prisma.PlaylistSongWhereUniqueInput | Prisma.PlaylistSongWhereUniqueInput[]
  update?: Prisma.PlaylistSongUpdateWithWhereUniqueWithoutSongInput | Prisma.PlaylistSongUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.PlaylistSongUpdateManyWithWhereWithoutSongInput | Prisma.PlaylistSongUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.PlaylistSongScalarWhereInput | Prisma.PlaylistSongScalarWhereInput[]
}

export type PlaylistSongCreateWithoutPlaylistInput = {
  id?: string
  position: number
  song: Prisma.SongCreateNestedOneWithoutPlaylistSongsInput
}

export type PlaylistSongUncheckedCreateWithoutPlaylistInput = {
  id?: string
  songId: string
  position: number
}

export type PlaylistSongCreateOrConnectWithoutPlaylistInput = {
  where: Prisma.PlaylistSongWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaylistSongCreateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput>
}

export type PlaylistSongCreateManyPlaylistInputEnvelope = {
  data: Prisma.PlaylistSongCreateManyPlaylistInput | Prisma.PlaylistSongCreateManyPlaylistInput[]
  skipDuplicates?: boolean
}

export type PlaylistSongUpsertWithWhereUniqueWithoutPlaylistInput = {
  where: Prisma.PlaylistSongWhereUniqueInput
  update: Prisma.XOR<Prisma.PlaylistSongUpdateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedUpdateWithoutPlaylistInput>
  create: Prisma.XOR<Prisma.PlaylistSongCreateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedCreateWithoutPlaylistInput>
}

export type PlaylistSongUpdateWithWhereUniqueWithoutPlaylistInput = {
  where: Prisma.PlaylistSongWhereUniqueInput
  data: Prisma.XOR<Prisma.PlaylistSongUpdateWithoutPlaylistInput, Prisma.PlaylistSongUncheckedUpdateWithoutPlaylistInput>
}

export type PlaylistSongUpdateManyWithWhereWithoutPlaylistInput = {
  where: Prisma.PlaylistSongScalarWhereInput
  data: Prisma.XOR<Prisma.PlaylistSongUpdateManyMutationInput, Prisma.PlaylistSongUncheckedUpdateManyWithoutPlaylistInput>
}

export type PlaylistSongScalarWhereInput = {
  AND?: Prisma.PlaylistSongScalarWhereInput | Prisma.PlaylistSongScalarWhereInput[]
  OR?: Prisma.PlaylistSongScalarWhereInput[]
  NOT?: Prisma.PlaylistSongScalarWhereInput | Prisma.PlaylistSongScalarWhereInput[]
  id?: Prisma.StringFilter<"PlaylistSong"> | string
  playlistId?: Prisma.StringFilter<"PlaylistSong"> | string
  songId?: Prisma.StringFilter<"PlaylistSong"> | string
  position?: Prisma.IntFilter<"PlaylistSong"> | number
}

export type PlaylistSongCreateWithoutSongInput = {
  id?: string
  position: number
  playlist: Prisma.PlaylistCreateNestedOneWithoutSongsInput
}

export type PlaylistSongUncheckedCreateWithoutSongInput = {
  id?: string
  playlistId: string
  position: number
}

export type PlaylistSongCreateOrConnectWithoutSongInput = {
  where: Prisma.PlaylistSongWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaylistSongCreateWithoutSongInput, Prisma.PlaylistSongUncheckedCreateWithoutSongInput>
}

export type PlaylistSongCreateManySongInputEnvelope = {
  data: Prisma.PlaylistSongCreateManySongInput | Prisma.PlaylistSongCreateManySongInput[]
  skipDuplicates?: boolean
}

export type PlaylistSongUpsertWithWhereUniqueWithoutSongInput = {
  where: Prisma.PlaylistSongWhereUniqueInput
  update: Prisma.XOR<Prisma.PlaylistSongUpdateWithoutSongInput, Prisma.PlaylistSongUncheckedUpdateWithoutSongInput>
  create: Prisma.XOR<Prisma.PlaylistSongCreateWithoutSongInput, Prisma.PlaylistSongUncheckedCreateWithoutSongInput>
}

export type PlaylistSongUpdateWithWhereUniqueWithoutSongInput = {
  where: Prisma.PlaylistSongWhereUniqueInput
  data: Prisma.XOR<Prisma.PlaylistSongUpdateWithoutSongInput, Prisma.PlaylistSongUncheckedUpdateWithoutSongInput>
}

export type PlaylistSongUpdateManyWithWhereWithoutSongInput = {
  where: Prisma.PlaylistSongScalarWhereInput
  data: Prisma.XOR<Prisma.PlaylistSongUpdateManyMutationInput, Prisma.PlaylistSongUncheckedUpdateManyWithoutSongInput>
}

export type PlaylistSongCreateManyPlaylistInput = {
  id?: string
  songId: string
  position: number
}

export type PlaylistSongUpdateWithoutPlaylistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  song?: Prisma.SongUpdateOneRequiredWithoutPlaylistSongsNestedInput
}

export type PlaylistSongUncheckedUpdateWithoutPlaylistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaylistSongUncheckedUpdateManyWithoutPlaylistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaylistSongCreateManySongInput = {
  id?: string
  playlistId: string
  position: number
}

export type PlaylistSongUpdateWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  playlist?: Prisma.PlaylistUpdateOneRequiredWithoutSongsNestedInput
}

export type PlaylistSongUncheckedUpdateWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlaylistSongUncheckedUpdateManyWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playlistId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}



export type PlaylistSongSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playlistId?: boolean
  songId?: boolean
  position?: boolean
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playlistSong"]>

export type PlaylistSongSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playlistId?: boolean
  songId?: boolean
  position?: boolean
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playlistSong"]>

export type PlaylistSongSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playlistId?: boolean
  songId?: boolean
  position?: boolean
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["playlistSong"]>

export type PlaylistSongSelectScalar = {
  id?: boolean
  playlistId?: boolean
  songId?: boolean
  position?: boolean
}

export type PlaylistSongOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "playlistId" | "songId" | "position", ExtArgs["result"]["playlistSong"]>
export type PlaylistSongInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}
export type PlaylistSongIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}
export type PlaylistSongIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  playlist?: boolean | Prisma.PlaylistDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}

export type $PlaylistSongPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlaylistSong"
  objects: {
    playlist: Prisma.$PlaylistPayload<ExtArgs>
    song: Prisma.$SongPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    playlistId: string
    songId: string
    position: number
  }, ExtArgs["result"]["playlistSong"]>
  composites: {}
}

export type PlaylistSongGetPayload<S extends boolean | null | undefined | PlaylistSongDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload, S>

export type PlaylistSongCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaylistSongFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaylistSongCountAggregateInputType | true
  }

export interface PlaylistSongDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlaylistSong'], meta: { name: 'PlaylistSong' } }
  /**
   * Find zero or one PlaylistSong that matches the filter.
   * @param {PlaylistSongFindUniqueArgs} args - Arguments to find a PlaylistSong
   * @example
   * // Get one PlaylistSong
   * const playlistSong = await prisma.playlistSong.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaylistSongFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaylistSongFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlaylistSong that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaylistSongFindUniqueOrThrowArgs} args - Arguments to find a PlaylistSong
   * @example
   * // Get one PlaylistSong
   * const playlistSong = await prisma.playlistSong.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaylistSongFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaylistSongFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaylistSong that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistSongFindFirstArgs} args - Arguments to find a PlaylistSong
   * @example
   * // Get one PlaylistSong
   * const playlistSong = await prisma.playlistSong.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaylistSongFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaylistSongFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaylistSong that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistSongFindFirstOrThrowArgs} args - Arguments to find a PlaylistSong
   * @example
   * // Get one PlaylistSong
   * const playlistSong = await prisma.playlistSong.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaylistSongFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaylistSongFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlaylistSongs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistSongFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlaylistSongs
   * const playlistSongs = await prisma.playlistSong.findMany()
   * 
   * // Get first 10 PlaylistSongs
   * const playlistSongs = await prisma.playlistSong.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const playlistSongWithIdOnly = await prisma.playlistSong.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlaylistSongFindManyArgs>(args?: Prisma.SelectSubset<T, PlaylistSongFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlaylistSong.
   * @param {PlaylistSongCreateArgs} args - Arguments to create a PlaylistSong.
   * @example
   * // Create one PlaylistSong
   * const PlaylistSong = await prisma.playlistSong.create({
   *   data: {
   *     // ... data to create a PlaylistSong
   *   }
   * })
   * 
   */
  create<T extends PlaylistSongCreateArgs>(args: Prisma.SelectSubset<T, PlaylistSongCreateArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlaylistSongs.
   * @param {PlaylistSongCreateManyArgs} args - Arguments to create many PlaylistSongs.
   * @example
   * // Create many PlaylistSongs
   * const playlistSong = await prisma.playlistSong.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaylistSongCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaylistSongCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PlaylistSongs and returns the data saved in the database.
   * @param {PlaylistSongCreateManyAndReturnArgs} args - Arguments to create many PlaylistSongs.
   * @example
   * // Create many PlaylistSongs
   * const playlistSong = await prisma.playlistSong.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PlaylistSongs and only return the `id`
   * const playlistSongWithIdOnly = await prisma.playlistSong.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaylistSongCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaylistSongCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PlaylistSong.
   * @param {PlaylistSongDeleteArgs} args - Arguments to delete one PlaylistSong.
   * @example
   * // Delete one PlaylistSong
   * const PlaylistSong = await prisma.playlistSong.delete({
   *   where: {
   *     // ... filter to delete one PlaylistSong
   *   }
   * })
   * 
   */
  delete<T extends PlaylistSongDeleteArgs>(args: Prisma.SelectSubset<T, PlaylistSongDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlaylistSong.
   * @param {PlaylistSongUpdateArgs} args - Arguments to update one PlaylistSong.
   * @example
   * // Update one PlaylistSong
   * const playlistSong = await prisma.playlistSong.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaylistSongUpdateArgs>(args: Prisma.SelectSubset<T, PlaylistSongUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlaylistSongs.
   * @param {PlaylistSongDeleteManyArgs} args - Arguments to filter PlaylistSongs to delete.
   * @example
   * // Delete a few PlaylistSongs
   * const { count } = await prisma.playlistSong.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaylistSongDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaylistSongDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaylistSongs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistSongUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlaylistSongs
   * const playlistSong = await prisma.playlistSong.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaylistSongUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaylistSongUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaylistSongs and returns the data updated in the database.
   * @param {PlaylistSongUpdateManyAndReturnArgs} args - Arguments to update many PlaylistSongs.
   * @example
   * // Update many PlaylistSongs
   * const playlistSong = await prisma.playlistSong.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PlaylistSongs and only return the `id`
   * const playlistSongWithIdOnly = await prisma.playlistSong.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaylistSongUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaylistSongUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PlaylistSong.
   * @param {PlaylistSongUpsertArgs} args - Arguments to update or create a PlaylistSong.
   * @example
   * // Update or create a PlaylistSong
   * const playlistSong = await prisma.playlistSong.upsert({
   *   create: {
   *     // ... data to create a PlaylistSong
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlaylistSong we want to update
   *   }
   * })
   */
  upsert<T extends PlaylistSongUpsertArgs>(args: Prisma.SelectSubset<T, PlaylistSongUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaylistSongClient<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlaylistSongs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistSongCountArgs} args - Arguments to filter PlaylistSongs to count.
   * @example
   * // Count the number of PlaylistSongs
   * const count = await prisma.playlistSong.count({
   *   where: {
   *     // ... the filter for the PlaylistSongs we want to count
   *   }
   * })
  **/
  count<T extends PlaylistSongCountArgs>(
    args?: Prisma.Subset<T, PlaylistSongCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaylistSongCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlaylistSong.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistSongAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaylistSongAggregateArgs>(args: Prisma.Subset<T, PlaylistSongAggregateArgs>): Prisma.PrismaPromise<GetPlaylistSongAggregateType<T>>

  /**
   * Group by PlaylistSong.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaylistSongGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaylistSongGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaylistSongGroupByArgs['orderBy'] }
      : { orderBy?: PlaylistSongGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaylistSongGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaylistSongGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlaylistSong model
 */
readonly fields: PlaylistSongFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlaylistSong.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaylistSongClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  playlist<T extends Prisma.PlaylistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlaylistDefaultArgs<ExtArgs>>): Prisma.Prisma__PlaylistClient<runtime.Types.Result.GetResult<Prisma.$PlaylistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  song<T extends Prisma.SongDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SongDefaultArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlaylistSong model
 */
export interface PlaylistSongFieldRefs {
  readonly id: Prisma.FieldRef<"PlaylistSong", 'String'>
  readonly playlistId: Prisma.FieldRef<"PlaylistSong", 'String'>
  readonly songId: Prisma.FieldRef<"PlaylistSong", 'String'>
  readonly position: Prisma.FieldRef<"PlaylistSong", 'Int'>
}
    

// Custom InputTypes
/**
 * PlaylistSong findUnique
 */
export type PlaylistSongFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistSong to fetch.
   */
  where: Prisma.PlaylistSongWhereUniqueInput
}

/**
 * PlaylistSong findUniqueOrThrow
 */
export type PlaylistSongFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistSong to fetch.
   */
  where: Prisma.PlaylistSongWhereUniqueInput
}

/**
 * PlaylistSong findFirst
 */
export type PlaylistSongFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistSong to fetch.
   */
  where?: Prisma.PlaylistSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistSongs to fetch.
   */
  orderBy?: Prisma.PlaylistSongOrderByWithRelationInput | Prisma.PlaylistSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaylistSongs.
   */
  cursor?: Prisma.PlaylistSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaylistSongs.
   */
  distinct?: Prisma.PlaylistSongScalarFieldEnum | Prisma.PlaylistSongScalarFieldEnum[]
}

/**
 * PlaylistSong findFirstOrThrow
 */
export type PlaylistSongFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistSong to fetch.
   */
  where?: Prisma.PlaylistSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistSongs to fetch.
   */
  orderBy?: Prisma.PlaylistSongOrderByWithRelationInput | Prisma.PlaylistSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaylistSongs.
   */
  cursor?: Prisma.PlaylistSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaylistSongs.
   */
  distinct?: Prisma.PlaylistSongScalarFieldEnum | Prisma.PlaylistSongScalarFieldEnum[]
}

/**
 * PlaylistSong findMany
 */
export type PlaylistSongFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * Filter, which PlaylistSongs to fetch.
   */
  where?: Prisma.PlaylistSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaylistSongs to fetch.
   */
  orderBy?: Prisma.PlaylistSongOrderByWithRelationInput | Prisma.PlaylistSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlaylistSongs.
   */
  cursor?: Prisma.PlaylistSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaylistSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaylistSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaylistSongs.
   */
  distinct?: Prisma.PlaylistSongScalarFieldEnum | Prisma.PlaylistSongScalarFieldEnum[]
}

/**
 * PlaylistSong create
 */
export type PlaylistSongCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * The data needed to create a PlaylistSong.
   */
  data: Prisma.XOR<Prisma.PlaylistSongCreateInput, Prisma.PlaylistSongUncheckedCreateInput>
}

/**
 * PlaylistSong createMany
 */
export type PlaylistSongCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlaylistSongs.
   */
  data: Prisma.PlaylistSongCreateManyInput | Prisma.PlaylistSongCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlaylistSong createManyAndReturn
 */
export type PlaylistSongCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * The data used to create many PlaylistSongs.
   */
  data: Prisma.PlaylistSongCreateManyInput | Prisma.PlaylistSongCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PlaylistSong update
 */
export type PlaylistSongUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * The data needed to update a PlaylistSong.
   */
  data: Prisma.XOR<Prisma.PlaylistSongUpdateInput, Prisma.PlaylistSongUncheckedUpdateInput>
  /**
   * Choose, which PlaylistSong to update.
   */
  where: Prisma.PlaylistSongWhereUniqueInput
}

/**
 * PlaylistSong updateMany
 */
export type PlaylistSongUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlaylistSongs.
   */
  data: Prisma.XOR<Prisma.PlaylistSongUpdateManyMutationInput, Prisma.PlaylistSongUncheckedUpdateManyInput>
  /**
   * Filter which PlaylistSongs to update
   */
  where?: Prisma.PlaylistSongWhereInput
  /**
   * Limit how many PlaylistSongs to update.
   */
  limit?: number
}

/**
 * PlaylistSong updateManyAndReturn
 */
export type PlaylistSongUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * The data used to update PlaylistSongs.
   */
  data: Prisma.XOR<Prisma.PlaylistSongUpdateManyMutationInput, Prisma.PlaylistSongUncheckedUpdateManyInput>
  /**
   * Filter which PlaylistSongs to update
   */
  where?: Prisma.PlaylistSongWhereInput
  /**
   * Limit how many PlaylistSongs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PlaylistSong upsert
 */
export type PlaylistSongUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * The filter to search for the PlaylistSong to update in case it exists.
   */
  where: Prisma.PlaylistSongWhereUniqueInput
  /**
   * In case the PlaylistSong found by the `where` argument doesn't exist, create a new PlaylistSong with this data.
   */
  create: Prisma.XOR<Prisma.PlaylistSongCreateInput, Prisma.PlaylistSongUncheckedCreateInput>
  /**
   * In case the PlaylistSong was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaylistSongUpdateInput, Prisma.PlaylistSongUncheckedUpdateInput>
}

/**
 * PlaylistSong delete
 */
export type PlaylistSongDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  /**
   * Filter which PlaylistSong to delete.
   */
  where: Prisma.PlaylistSongWhereUniqueInput
}

/**
 * PlaylistSong deleteMany
 */
export type PlaylistSongDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaylistSongs to delete
   */
  where?: Prisma.PlaylistSongWhereInput
  /**
   * Limit how many PlaylistSongs to delete.
   */
  limit?: number
}

/**
 * PlaylistSong without action
 */
export type PlaylistSongDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
}
