
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Queue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Queue
 * 
 */
export type QueueModel = runtime.Types.Result.DefaultSelection<Prisma.$QueuePayload>

export type AggregateQueue = {
  _count: QueueCountAggregateOutputType | null
  _min: QueueMinAggregateOutputType | null
  _max: QueueMaxAggregateOutputType | null
}

export type QueueMinAggregateOutputType = {
  id: string | null
  userId: string | null
}

export type QueueMaxAggregateOutputType = {
  id: string | null
  userId: string | null
}

export type QueueCountAggregateOutputType = {
  id: number
  userId: number
  _all: number
}


export type QueueMinAggregateInputType = {
  id?: true
  userId?: true
}

export type QueueMaxAggregateInputType = {
  id?: true
  userId?: true
}

export type QueueCountAggregateInputType = {
  id?: true
  userId?: true
  _all?: true
}

export type QueueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Queue to aggregate.
   */
  where?: Prisma.QueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Queues to fetch.
   */
  orderBy?: Prisma.QueueOrderByWithRelationInput | Prisma.QueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Queues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Queues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Queues
  **/
  _count?: true | QueueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QueueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QueueMaxAggregateInputType
}

export type GetQueueAggregateType<T extends QueueAggregateArgs> = {
      [P in keyof T & keyof AggregateQueue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQueue[P]>
    : Prisma.GetScalarType<T[P], AggregateQueue[P]>
}




export type QueueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QueueWhereInput
  orderBy?: Prisma.QueueOrderByWithAggregationInput | Prisma.QueueOrderByWithAggregationInput[]
  by: Prisma.QueueScalarFieldEnum[] | Prisma.QueueScalarFieldEnum
  having?: Prisma.QueueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QueueCountAggregateInputType | true
  _min?: QueueMinAggregateInputType
  _max?: QueueMaxAggregateInputType
}

export type QueueGroupByOutputType = {
  id: string
  userId: string
  _count: QueueCountAggregateOutputType | null
  _min: QueueMinAggregateOutputType | null
  _max: QueueMaxAggregateOutputType | null
}

export type GetQueueGroupByPayload<T extends QueueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QueueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QueueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QueueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QueueGroupByOutputType[P]>
      }
    >
  >



export type QueueWhereInput = {
  AND?: Prisma.QueueWhereInput | Prisma.QueueWhereInput[]
  OR?: Prisma.QueueWhereInput[]
  NOT?: Prisma.QueueWhereInput | Prisma.QueueWhereInput[]
  id?: Prisma.StringFilter<"Queue"> | string
  userId?: Prisma.StringFilter<"Queue"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  songs?: Prisma.QueueSongListRelationFilter
}

export type QueueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  songs?: Prisma.QueueSongOrderByRelationAggregateInput
}

export type QueueWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.QueueWhereInput | Prisma.QueueWhereInput[]
  OR?: Prisma.QueueWhereInput[]
  NOT?: Prisma.QueueWhereInput | Prisma.QueueWhereInput[]
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  songs?: Prisma.QueueSongListRelationFilter
}, "id" | "userId">

export type QueueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.QueueCountOrderByAggregateInput
  _max?: Prisma.QueueMaxOrderByAggregateInput
  _min?: Prisma.QueueMinOrderByAggregateInput
}

export type QueueScalarWhereWithAggregatesInput = {
  AND?: Prisma.QueueScalarWhereWithAggregatesInput | Prisma.QueueScalarWhereWithAggregatesInput[]
  OR?: Prisma.QueueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QueueScalarWhereWithAggregatesInput | Prisma.QueueScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Queue"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Queue"> | string
}

export type QueueCreateInput = {
  id?: string
  user: Prisma.UserCreateNestedOneWithoutQueueInput
  songs?: Prisma.QueueSongCreateNestedManyWithoutQueueInput
}

export type QueueUncheckedCreateInput = {
  id?: string
  userId: string
  songs?: Prisma.QueueSongUncheckedCreateNestedManyWithoutQueueInput
}

export type QueueUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutQueueNestedInput
  songs?: Prisma.QueueSongUpdateManyWithoutQueueNestedInput
}

export type QueueUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  songs?: Prisma.QueueSongUncheckedUpdateManyWithoutQueueNestedInput
}

export type QueueCreateManyInput = {
  id?: string
  userId: string
}

export type QueueUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QueueUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type QueueNullableScalarRelationFilter = {
  is?: Prisma.QueueWhereInput | null
  isNot?: Prisma.QueueWhereInput | null
}

export type QueueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type QueueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type QueueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type QueueScalarRelationFilter = {
  is?: Prisma.QueueWhereInput
  isNot?: Prisma.QueueWhereInput
}

export type QueueCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QueueCreateWithoutUserInput, Prisma.QueueUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.QueueCreateOrConnectWithoutUserInput
  connect?: Prisma.QueueWhereUniqueInput
}

export type QueueUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QueueCreateWithoutUserInput, Prisma.QueueUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.QueueCreateOrConnectWithoutUserInput
  connect?: Prisma.QueueWhereUniqueInput
}

export type QueueUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QueueCreateWithoutUserInput, Prisma.QueueUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.QueueCreateOrConnectWithoutUserInput
  upsert?: Prisma.QueueUpsertWithoutUserInput
  disconnect?: Prisma.QueueWhereInput | boolean
  delete?: Prisma.QueueWhereInput | boolean
  connect?: Prisma.QueueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QueueUpdateToOneWithWhereWithoutUserInput, Prisma.QueueUpdateWithoutUserInput>, Prisma.QueueUncheckedUpdateWithoutUserInput>
}

export type QueueUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QueueCreateWithoutUserInput, Prisma.QueueUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.QueueCreateOrConnectWithoutUserInput
  upsert?: Prisma.QueueUpsertWithoutUserInput
  disconnect?: Prisma.QueueWhereInput | boolean
  delete?: Prisma.QueueWhereInput | boolean
  connect?: Prisma.QueueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QueueUpdateToOneWithWhereWithoutUserInput, Prisma.QueueUpdateWithoutUserInput>, Prisma.QueueUncheckedUpdateWithoutUserInput>
}

export type QueueCreateNestedOneWithoutSongsInput = {
  create?: Prisma.XOR<Prisma.QueueCreateWithoutSongsInput, Prisma.QueueUncheckedCreateWithoutSongsInput>
  connectOrCreate?: Prisma.QueueCreateOrConnectWithoutSongsInput
  connect?: Prisma.QueueWhereUniqueInput
}

export type QueueUpdateOneRequiredWithoutSongsNestedInput = {
  create?: Prisma.XOR<Prisma.QueueCreateWithoutSongsInput, Prisma.QueueUncheckedCreateWithoutSongsInput>
  connectOrCreate?: Prisma.QueueCreateOrConnectWithoutSongsInput
  upsert?: Prisma.QueueUpsertWithoutSongsInput
  connect?: Prisma.QueueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QueueUpdateToOneWithWhereWithoutSongsInput, Prisma.QueueUpdateWithoutSongsInput>, Prisma.QueueUncheckedUpdateWithoutSongsInput>
}

export type QueueCreateWithoutUserInput = {
  id?: string
  songs?: Prisma.QueueSongCreateNestedManyWithoutQueueInput
}

export type QueueUncheckedCreateWithoutUserInput = {
  id?: string
  songs?: Prisma.QueueSongUncheckedCreateNestedManyWithoutQueueInput
}

export type QueueCreateOrConnectWithoutUserInput = {
  where: Prisma.QueueWhereUniqueInput
  create: Prisma.XOR<Prisma.QueueCreateWithoutUserInput, Prisma.QueueUncheckedCreateWithoutUserInput>
}

export type QueueUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.QueueUpdateWithoutUserInput, Prisma.QueueUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.QueueCreateWithoutUserInput, Prisma.QueueUncheckedCreateWithoutUserInput>
  where?: Prisma.QueueWhereInput
}

export type QueueUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.QueueWhereInput
  data: Prisma.XOR<Prisma.QueueUpdateWithoutUserInput, Prisma.QueueUncheckedUpdateWithoutUserInput>
}

export type QueueUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  songs?: Prisma.QueueSongUpdateManyWithoutQueueNestedInput
}

export type QueueUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  songs?: Prisma.QueueSongUncheckedUpdateManyWithoutQueueNestedInput
}

export type QueueCreateWithoutSongsInput = {
  id?: string
  user: Prisma.UserCreateNestedOneWithoutQueueInput
}

export type QueueUncheckedCreateWithoutSongsInput = {
  id?: string
  userId: string
}

export type QueueCreateOrConnectWithoutSongsInput = {
  where: Prisma.QueueWhereUniqueInput
  create: Prisma.XOR<Prisma.QueueCreateWithoutSongsInput, Prisma.QueueUncheckedCreateWithoutSongsInput>
}

export type QueueUpsertWithoutSongsInput = {
  update: Prisma.XOR<Prisma.QueueUpdateWithoutSongsInput, Prisma.QueueUncheckedUpdateWithoutSongsInput>
  create: Prisma.XOR<Prisma.QueueCreateWithoutSongsInput, Prisma.QueueUncheckedCreateWithoutSongsInput>
  where?: Prisma.QueueWhereInput
}

export type QueueUpdateToOneWithWhereWithoutSongsInput = {
  where?: Prisma.QueueWhereInput
  data: Prisma.XOR<Prisma.QueueUpdateWithoutSongsInput, Prisma.QueueUncheckedUpdateWithoutSongsInput>
}

export type QueueUpdateWithoutSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutQueueNestedInput
}

export type QueueUncheckedUpdateWithoutSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type QueueCountOutputType
 */

export type QueueCountOutputType = {
  songs: number
}

export type QueueCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  songs?: boolean | QueueCountOutputTypeCountSongsArgs
}

/**
 * QueueCountOutputType without action
 */
export type QueueCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueCountOutputType
   */
  select?: Prisma.QueueCountOutputTypeSelect<ExtArgs> | null
}

/**
 * QueueCountOutputType without action
 */
export type QueueCountOutputTypeCountSongsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QueueSongWhereInput
}


export type QueueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  songs?: boolean | Prisma.Queue$songsArgs<ExtArgs>
  _count?: boolean | Prisma.QueueCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["queue"]>

export type QueueSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["queue"]>

export type QueueSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["queue"]>

export type QueueSelectScalar = {
  id?: boolean
  userId?: boolean
}

export type QueueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId", ExtArgs["result"]["queue"]>
export type QueueInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  songs?: boolean | Prisma.Queue$songsArgs<ExtArgs>
  _count?: boolean | Prisma.QueueCountOutputTypeDefaultArgs<ExtArgs>
}
export type QueueIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type QueueIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $QueuePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Queue"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    songs: Prisma.$QueueSongPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
  }, ExtArgs["result"]["queue"]>
  composites: {}
}

export type QueueGetPayload<S extends boolean | null | undefined | QueueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QueuePayload, S>

export type QueueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QueueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QueueCountAggregateInputType | true
  }

export interface QueueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Queue'], meta: { name: 'Queue' } }
  /**
   * Find zero or one Queue that matches the filter.
   * @param {QueueFindUniqueArgs} args - Arguments to find a Queue
   * @example
   * // Get one Queue
   * const queue = await prisma.queue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QueueFindUniqueArgs>(args: Prisma.SelectSubset<T, QueueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Queue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QueueFindUniqueOrThrowArgs} args - Arguments to find a Queue
   * @example
   * // Get one Queue
   * const queue = await prisma.queue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QueueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QueueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Queue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueFindFirstArgs} args - Arguments to find a Queue
   * @example
   * // Get one Queue
   * const queue = await prisma.queue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QueueFindFirstArgs>(args?: Prisma.SelectSubset<T, QueueFindFirstArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Queue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueFindFirstOrThrowArgs} args - Arguments to find a Queue
   * @example
   * // Get one Queue
   * const queue = await prisma.queue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QueueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QueueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Queues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Queues
   * const queues = await prisma.queue.findMany()
   * 
   * // Get first 10 Queues
   * const queues = await prisma.queue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const queueWithIdOnly = await prisma.queue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QueueFindManyArgs>(args?: Prisma.SelectSubset<T, QueueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Queue.
   * @param {QueueCreateArgs} args - Arguments to create a Queue.
   * @example
   * // Create one Queue
   * const Queue = await prisma.queue.create({
   *   data: {
   *     // ... data to create a Queue
   *   }
   * })
   * 
   */
  create<T extends QueueCreateArgs>(args: Prisma.SelectSubset<T, QueueCreateArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Queues.
   * @param {QueueCreateManyArgs} args - Arguments to create many Queues.
   * @example
   * // Create many Queues
   * const queue = await prisma.queue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QueueCreateManyArgs>(args?: Prisma.SelectSubset<T, QueueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Queues and returns the data saved in the database.
   * @param {QueueCreateManyAndReturnArgs} args - Arguments to create many Queues.
   * @example
   * // Create many Queues
   * const queue = await prisma.queue.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Queues and only return the `id`
   * const queueWithIdOnly = await prisma.queue.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QueueCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QueueCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Queue.
   * @param {QueueDeleteArgs} args - Arguments to delete one Queue.
   * @example
   * // Delete one Queue
   * const Queue = await prisma.queue.delete({
   *   where: {
   *     // ... filter to delete one Queue
   *   }
   * })
   * 
   */
  delete<T extends QueueDeleteArgs>(args: Prisma.SelectSubset<T, QueueDeleteArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Queue.
   * @param {QueueUpdateArgs} args - Arguments to update one Queue.
   * @example
   * // Update one Queue
   * const queue = await prisma.queue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QueueUpdateArgs>(args: Prisma.SelectSubset<T, QueueUpdateArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Queues.
   * @param {QueueDeleteManyArgs} args - Arguments to filter Queues to delete.
   * @example
   * // Delete a few Queues
   * const { count } = await prisma.queue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QueueDeleteManyArgs>(args?: Prisma.SelectSubset<T, QueueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Queues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Queues
   * const queue = await prisma.queue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QueueUpdateManyArgs>(args: Prisma.SelectSubset<T, QueueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Queues and returns the data updated in the database.
   * @param {QueueUpdateManyAndReturnArgs} args - Arguments to update many Queues.
   * @example
   * // Update many Queues
   * const queue = await prisma.queue.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Queues and only return the `id`
   * const queueWithIdOnly = await prisma.queue.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QueueUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QueueUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Queue.
   * @param {QueueUpsertArgs} args - Arguments to update or create a Queue.
   * @example
   * // Update or create a Queue
   * const queue = await prisma.queue.upsert({
   *   create: {
   *     // ... data to create a Queue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Queue we want to update
   *   }
   * })
   */
  upsert<T extends QueueUpsertArgs>(args: Prisma.SelectSubset<T, QueueUpsertArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Queues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueCountArgs} args - Arguments to filter Queues to count.
   * @example
   * // Count the number of Queues
   * const count = await prisma.queue.count({
   *   where: {
   *     // ... the filter for the Queues we want to count
   *   }
   * })
  **/
  count<T extends QueueCountArgs>(
    args?: Prisma.Subset<T, QueueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QueueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Queue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QueueAggregateArgs>(args: Prisma.Subset<T, QueueAggregateArgs>): Prisma.PrismaPromise<GetQueueAggregateType<T>>

  /**
   * Group by Queue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QueueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QueueGroupByArgs['orderBy'] }
      : { orderBy?: QueueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QueueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQueueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Queue model
 */
readonly fields: QueueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Queue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QueueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  songs<T extends Prisma.Queue$songsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Queue$songsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Queue model
 */
export interface QueueFieldRefs {
  readonly id: Prisma.FieldRef<"Queue", 'String'>
  readonly userId: Prisma.FieldRef<"Queue", 'String'>
}
    

// Custom InputTypes
/**
 * Queue findUnique
 */
export type QueueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * Filter, which Queue to fetch.
   */
  where: Prisma.QueueWhereUniqueInput
}

/**
 * Queue findUniqueOrThrow
 */
export type QueueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * Filter, which Queue to fetch.
   */
  where: Prisma.QueueWhereUniqueInput
}

/**
 * Queue findFirst
 */
export type QueueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * Filter, which Queue to fetch.
   */
  where?: Prisma.QueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Queues to fetch.
   */
  orderBy?: Prisma.QueueOrderByWithRelationInput | Prisma.QueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Queues.
   */
  cursor?: Prisma.QueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Queues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Queues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Queues.
   */
  distinct?: Prisma.QueueScalarFieldEnum | Prisma.QueueScalarFieldEnum[]
}

/**
 * Queue findFirstOrThrow
 */
export type QueueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * Filter, which Queue to fetch.
   */
  where?: Prisma.QueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Queues to fetch.
   */
  orderBy?: Prisma.QueueOrderByWithRelationInput | Prisma.QueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Queues.
   */
  cursor?: Prisma.QueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Queues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Queues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Queues.
   */
  distinct?: Prisma.QueueScalarFieldEnum | Prisma.QueueScalarFieldEnum[]
}

/**
 * Queue findMany
 */
export type QueueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * Filter, which Queues to fetch.
   */
  where?: Prisma.QueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Queues to fetch.
   */
  orderBy?: Prisma.QueueOrderByWithRelationInput | Prisma.QueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Queues.
   */
  cursor?: Prisma.QueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Queues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Queues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Queues.
   */
  distinct?: Prisma.QueueScalarFieldEnum | Prisma.QueueScalarFieldEnum[]
}

/**
 * Queue create
 */
export type QueueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * The data needed to create a Queue.
   */
  data: Prisma.XOR<Prisma.QueueCreateInput, Prisma.QueueUncheckedCreateInput>
}

/**
 * Queue createMany
 */
export type QueueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Queues.
   */
  data: Prisma.QueueCreateManyInput | Prisma.QueueCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Queue createManyAndReturn
 */
export type QueueCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * The data used to create many Queues.
   */
  data: Prisma.QueueCreateManyInput | Prisma.QueueCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Queue update
 */
export type QueueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * The data needed to update a Queue.
   */
  data: Prisma.XOR<Prisma.QueueUpdateInput, Prisma.QueueUncheckedUpdateInput>
  /**
   * Choose, which Queue to update.
   */
  where: Prisma.QueueWhereUniqueInput
}

/**
 * Queue updateMany
 */
export type QueueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Queues.
   */
  data: Prisma.XOR<Prisma.QueueUpdateManyMutationInput, Prisma.QueueUncheckedUpdateManyInput>
  /**
   * Filter which Queues to update
   */
  where?: Prisma.QueueWhereInput
  /**
   * Limit how many Queues to update.
   */
  limit?: number
}

/**
 * Queue updateManyAndReturn
 */
export type QueueUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * The data used to update Queues.
   */
  data: Prisma.XOR<Prisma.QueueUpdateManyMutationInput, Prisma.QueueUncheckedUpdateManyInput>
  /**
   * Filter which Queues to update
   */
  where?: Prisma.QueueWhereInput
  /**
   * Limit how many Queues to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Queue upsert
 */
export type QueueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * The filter to search for the Queue to update in case it exists.
   */
  where: Prisma.QueueWhereUniqueInput
  /**
   * In case the Queue found by the `where` argument doesn't exist, create a new Queue with this data.
   */
  create: Prisma.XOR<Prisma.QueueCreateInput, Prisma.QueueUncheckedCreateInput>
  /**
   * In case the Queue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QueueUpdateInput, Prisma.QueueUncheckedUpdateInput>
}

/**
 * Queue delete
 */
export type QueueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
  /**
   * Filter which Queue to delete.
   */
  where: Prisma.QueueWhereUniqueInput
}

/**
 * Queue deleteMany
 */
export type QueueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Queues to delete
   */
  where?: Prisma.QueueWhereInput
  /**
   * Limit how many Queues to delete.
   */
  limit?: number
}

/**
 * Queue.songs
 */
export type Queue$songsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  where?: Prisma.QueueSongWhereInput
  orderBy?: Prisma.QueueSongOrderByWithRelationInput | Prisma.QueueSongOrderByWithRelationInput[]
  cursor?: Prisma.QueueSongWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QueueSongScalarFieldEnum | Prisma.QueueSongScalarFieldEnum[]
}

/**
 * Queue without action
 */
export type QueueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Queue
   */
  select?: Prisma.QueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Queue
   */
  omit?: Prisma.QueueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueInclude<ExtArgs> | null
}
