
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QueueSong` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QueueSong
 * 
 */
export type QueueSongModel = runtime.Types.Result.DefaultSelection<Prisma.$QueueSongPayload>

export type AggregateQueueSong = {
  _count: QueueSongCountAggregateOutputType | null
  _avg: QueueSongAvgAggregateOutputType | null
  _sum: QueueSongSumAggregateOutputType | null
  _min: QueueSongMinAggregateOutputType | null
  _max: QueueSongMaxAggregateOutputType | null
}

export type QueueSongAvgAggregateOutputType = {
  position: number | null
}

export type QueueSongSumAggregateOutputType = {
  position: number | null
}

export type QueueSongMinAggregateOutputType = {
  id: string | null
  queueId: string | null
  songId: string | null
  position: number | null
}

export type QueueSongMaxAggregateOutputType = {
  id: string | null
  queueId: string | null
  songId: string | null
  position: number | null
}

export type QueueSongCountAggregateOutputType = {
  id: number
  queueId: number
  songId: number
  position: number
  _all: number
}


export type QueueSongAvgAggregateInputType = {
  position?: true
}

export type QueueSongSumAggregateInputType = {
  position?: true
}

export type QueueSongMinAggregateInputType = {
  id?: true
  queueId?: true
  songId?: true
  position?: true
}

export type QueueSongMaxAggregateInputType = {
  id?: true
  queueId?: true
  songId?: true
  position?: true
}

export type QueueSongCountAggregateInputType = {
  id?: true
  queueId?: true
  songId?: true
  position?: true
  _all?: true
}

export type QueueSongAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QueueSong to aggregate.
   */
  where?: Prisma.QueueSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueSongs to fetch.
   */
  orderBy?: Prisma.QueueSongOrderByWithRelationInput | Prisma.QueueSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QueueSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QueueSongs
  **/
  _count?: true | QueueSongCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QueueSongAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QueueSongSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QueueSongMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QueueSongMaxAggregateInputType
}

export type GetQueueSongAggregateType<T extends QueueSongAggregateArgs> = {
      [P in keyof T & keyof AggregateQueueSong]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQueueSong[P]>
    : Prisma.GetScalarType<T[P], AggregateQueueSong[P]>
}




export type QueueSongGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QueueSongWhereInput
  orderBy?: Prisma.QueueSongOrderByWithAggregationInput | Prisma.QueueSongOrderByWithAggregationInput[]
  by: Prisma.QueueSongScalarFieldEnum[] | Prisma.QueueSongScalarFieldEnum
  having?: Prisma.QueueSongScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QueueSongCountAggregateInputType | true
  _avg?: QueueSongAvgAggregateInputType
  _sum?: QueueSongSumAggregateInputType
  _min?: QueueSongMinAggregateInputType
  _max?: QueueSongMaxAggregateInputType
}

export type QueueSongGroupByOutputType = {
  id: string
  queueId: string
  songId: string
  position: number
  _count: QueueSongCountAggregateOutputType | null
  _avg: QueueSongAvgAggregateOutputType | null
  _sum: QueueSongSumAggregateOutputType | null
  _min: QueueSongMinAggregateOutputType | null
  _max: QueueSongMaxAggregateOutputType | null
}

export type GetQueueSongGroupByPayload<T extends QueueSongGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QueueSongGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QueueSongGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QueueSongGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QueueSongGroupByOutputType[P]>
      }
    >
  >



export type QueueSongWhereInput = {
  AND?: Prisma.QueueSongWhereInput | Prisma.QueueSongWhereInput[]
  OR?: Prisma.QueueSongWhereInput[]
  NOT?: Prisma.QueueSongWhereInput | Prisma.QueueSongWhereInput[]
  id?: Prisma.StringFilter<"QueueSong"> | string
  queueId?: Prisma.StringFilter<"QueueSong"> | string
  songId?: Prisma.StringFilter<"QueueSong"> | string
  position?: Prisma.IntFilter<"QueueSong"> | number
  queue?: Prisma.XOR<Prisma.QueueScalarRelationFilter, Prisma.QueueWhereInput>
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
}

export type QueueSongOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  queueId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  queue?: Prisma.QueueOrderByWithRelationInput
  song?: Prisma.SongOrderByWithRelationInput
}

export type QueueSongWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.QueueSongWhereInput | Prisma.QueueSongWhereInput[]
  OR?: Prisma.QueueSongWhereInput[]
  NOT?: Prisma.QueueSongWhereInput | Prisma.QueueSongWhereInput[]
  queueId?: Prisma.StringFilter<"QueueSong"> | string
  songId?: Prisma.StringFilter<"QueueSong"> | string
  position?: Prisma.IntFilter<"QueueSong"> | number
  queue?: Prisma.XOR<Prisma.QueueScalarRelationFilter, Prisma.QueueWhereInput>
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
}, "id">

export type QueueSongOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  queueId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  _count?: Prisma.QueueSongCountOrderByAggregateInput
  _avg?: Prisma.QueueSongAvgOrderByAggregateInput
  _max?: Prisma.QueueSongMaxOrderByAggregateInput
  _min?: Prisma.QueueSongMinOrderByAggregateInput
  _sum?: Prisma.QueueSongSumOrderByAggregateInput
}

export type QueueSongScalarWhereWithAggregatesInput = {
  AND?: Prisma.QueueSongScalarWhereWithAggregatesInput | Prisma.QueueSongScalarWhereWithAggregatesInput[]
  OR?: Prisma.QueueSongScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QueueSongScalarWhereWithAggregatesInput | Prisma.QueueSongScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QueueSong"> | string
  queueId?: Prisma.StringWithAggregatesFilter<"QueueSong"> | string
  songId?: Prisma.StringWithAggregatesFilter<"QueueSong"> | string
  position?: Prisma.IntWithAggregatesFilter<"QueueSong"> | number
}

export type QueueSongCreateInput = {
  id?: string
  position: number
  queue: Prisma.QueueCreateNestedOneWithoutSongsInput
  song: Prisma.SongCreateNestedOneWithoutQueueSongsInput
}

export type QueueSongUncheckedCreateInput = {
  id?: string
  queueId: string
  songId: string
  position: number
}

export type QueueSongUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  queue?: Prisma.QueueUpdateOneRequiredWithoutSongsNestedInput
  song?: Prisma.SongUpdateOneRequiredWithoutQueueSongsNestedInput
}

export type QueueSongUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  queueId?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type QueueSongCreateManyInput = {
  id?: string
  queueId: string
  songId: string
  position: number
}

export type QueueSongUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type QueueSongUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  queueId?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type QueueSongListRelationFilter = {
  every?: Prisma.QueueSongWhereInput
  some?: Prisma.QueueSongWhereInput
  none?: Prisma.QueueSongWhereInput
}

export type QueueSongOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QueueSongCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  queueId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type QueueSongAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type QueueSongMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  queueId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type QueueSongMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  queueId?: Prisma.SortOrder
  songId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type QueueSongSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type QueueSongCreateNestedManyWithoutQueueInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutQueueInput, Prisma.QueueSongUncheckedCreateWithoutQueueInput> | Prisma.QueueSongCreateWithoutQueueInput[] | Prisma.QueueSongUncheckedCreateWithoutQueueInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutQueueInput | Prisma.QueueSongCreateOrConnectWithoutQueueInput[]
  createMany?: Prisma.QueueSongCreateManyQueueInputEnvelope
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
}

export type QueueSongUncheckedCreateNestedManyWithoutQueueInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutQueueInput, Prisma.QueueSongUncheckedCreateWithoutQueueInput> | Prisma.QueueSongCreateWithoutQueueInput[] | Prisma.QueueSongUncheckedCreateWithoutQueueInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutQueueInput | Prisma.QueueSongCreateOrConnectWithoutQueueInput[]
  createMany?: Prisma.QueueSongCreateManyQueueInputEnvelope
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
}

export type QueueSongUpdateManyWithoutQueueNestedInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutQueueInput, Prisma.QueueSongUncheckedCreateWithoutQueueInput> | Prisma.QueueSongCreateWithoutQueueInput[] | Prisma.QueueSongUncheckedCreateWithoutQueueInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutQueueInput | Prisma.QueueSongCreateOrConnectWithoutQueueInput[]
  upsert?: Prisma.QueueSongUpsertWithWhereUniqueWithoutQueueInput | Prisma.QueueSongUpsertWithWhereUniqueWithoutQueueInput[]
  createMany?: Prisma.QueueSongCreateManyQueueInputEnvelope
  set?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  disconnect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  delete?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  update?: Prisma.QueueSongUpdateWithWhereUniqueWithoutQueueInput | Prisma.QueueSongUpdateWithWhereUniqueWithoutQueueInput[]
  updateMany?: Prisma.QueueSongUpdateManyWithWhereWithoutQueueInput | Prisma.QueueSongUpdateManyWithWhereWithoutQueueInput[]
  deleteMany?: Prisma.QueueSongScalarWhereInput | Prisma.QueueSongScalarWhereInput[]
}

export type QueueSongUncheckedUpdateManyWithoutQueueNestedInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutQueueInput, Prisma.QueueSongUncheckedCreateWithoutQueueInput> | Prisma.QueueSongCreateWithoutQueueInput[] | Prisma.QueueSongUncheckedCreateWithoutQueueInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutQueueInput | Prisma.QueueSongCreateOrConnectWithoutQueueInput[]
  upsert?: Prisma.QueueSongUpsertWithWhereUniqueWithoutQueueInput | Prisma.QueueSongUpsertWithWhereUniqueWithoutQueueInput[]
  createMany?: Prisma.QueueSongCreateManyQueueInputEnvelope
  set?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  disconnect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  delete?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  update?: Prisma.QueueSongUpdateWithWhereUniqueWithoutQueueInput | Prisma.QueueSongUpdateWithWhereUniqueWithoutQueueInput[]
  updateMany?: Prisma.QueueSongUpdateManyWithWhereWithoutQueueInput | Prisma.QueueSongUpdateManyWithWhereWithoutQueueInput[]
  deleteMany?: Prisma.QueueSongScalarWhereInput | Prisma.QueueSongScalarWhereInput[]
}

export type QueueSongCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutSongInput, Prisma.QueueSongUncheckedCreateWithoutSongInput> | Prisma.QueueSongCreateWithoutSongInput[] | Prisma.QueueSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutSongInput | Prisma.QueueSongCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.QueueSongCreateManySongInputEnvelope
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
}

export type QueueSongUncheckedCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutSongInput, Prisma.QueueSongUncheckedCreateWithoutSongInput> | Prisma.QueueSongCreateWithoutSongInput[] | Prisma.QueueSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutSongInput | Prisma.QueueSongCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.QueueSongCreateManySongInputEnvelope
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
}

export type QueueSongUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutSongInput, Prisma.QueueSongUncheckedCreateWithoutSongInput> | Prisma.QueueSongCreateWithoutSongInput[] | Prisma.QueueSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutSongInput | Prisma.QueueSongCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.QueueSongUpsertWithWhereUniqueWithoutSongInput | Prisma.QueueSongUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.QueueSongCreateManySongInputEnvelope
  set?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  disconnect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  delete?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  update?: Prisma.QueueSongUpdateWithWhereUniqueWithoutSongInput | Prisma.QueueSongUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.QueueSongUpdateManyWithWhereWithoutSongInput | Prisma.QueueSongUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.QueueSongScalarWhereInput | Prisma.QueueSongScalarWhereInput[]
}

export type QueueSongUncheckedUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.QueueSongCreateWithoutSongInput, Prisma.QueueSongUncheckedCreateWithoutSongInput> | Prisma.QueueSongCreateWithoutSongInput[] | Prisma.QueueSongUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.QueueSongCreateOrConnectWithoutSongInput | Prisma.QueueSongCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.QueueSongUpsertWithWhereUniqueWithoutSongInput | Prisma.QueueSongUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.QueueSongCreateManySongInputEnvelope
  set?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  disconnect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  delete?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  connect?: Prisma.QueueSongWhereUniqueInput | Prisma.QueueSongWhereUniqueInput[]
  update?: Prisma.QueueSongUpdateWithWhereUniqueWithoutSongInput | Prisma.QueueSongUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.QueueSongUpdateManyWithWhereWithoutSongInput | Prisma.QueueSongUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.QueueSongScalarWhereInput | Prisma.QueueSongScalarWhereInput[]
}

export type QueueSongCreateWithoutQueueInput = {
  id?: string
  position: number
  song: Prisma.SongCreateNestedOneWithoutQueueSongsInput
}

export type QueueSongUncheckedCreateWithoutQueueInput = {
  id?: string
  songId: string
  position: number
}

export type QueueSongCreateOrConnectWithoutQueueInput = {
  where: Prisma.QueueSongWhereUniqueInput
  create: Prisma.XOR<Prisma.QueueSongCreateWithoutQueueInput, Prisma.QueueSongUncheckedCreateWithoutQueueInput>
}

export type QueueSongCreateManyQueueInputEnvelope = {
  data: Prisma.QueueSongCreateManyQueueInput | Prisma.QueueSongCreateManyQueueInput[]
  skipDuplicates?: boolean
}

export type QueueSongUpsertWithWhereUniqueWithoutQueueInput = {
  where: Prisma.QueueSongWhereUniqueInput
  update: Prisma.XOR<Prisma.QueueSongUpdateWithoutQueueInput, Prisma.QueueSongUncheckedUpdateWithoutQueueInput>
  create: Prisma.XOR<Prisma.QueueSongCreateWithoutQueueInput, Prisma.QueueSongUncheckedCreateWithoutQueueInput>
}

export type QueueSongUpdateWithWhereUniqueWithoutQueueInput = {
  where: Prisma.QueueSongWhereUniqueInput
  data: Prisma.XOR<Prisma.QueueSongUpdateWithoutQueueInput, Prisma.QueueSongUncheckedUpdateWithoutQueueInput>
}

export type QueueSongUpdateManyWithWhereWithoutQueueInput = {
  where: Prisma.QueueSongScalarWhereInput
  data: Prisma.XOR<Prisma.QueueSongUpdateManyMutationInput, Prisma.QueueSongUncheckedUpdateManyWithoutQueueInput>
}

export type QueueSongScalarWhereInput = {
  AND?: Prisma.QueueSongScalarWhereInput | Prisma.QueueSongScalarWhereInput[]
  OR?: Prisma.QueueSongScalarWhereInput[]
  NOT?: Prisma.QueueSongScalarWhereInput | Prisma.QueueSongScalarWhereInput[]
  id?: Prisma.StringFilter<"QueueSong"> | string
  queueId?: Prisma.StringFilter<"QueueSong"> | string
  songId?: Prisma.StringFilter<"QueueSong"> | string
  position?: Prisma.IntFilter<"QueueSong"> | number
}

export type QueueSongCreateWithoutSongInput = {
  id?: string
  position: number
  queue: Prisma.QueueCreateNestedOneWithoutSongsInput
}

export type QueueSongUncheckedCreateWithoutSongInput = {
  id?: string
  queueId: string
  position: number
}

export type QueueSongCreateOrConnectWithoutSongInput = {
  where: Prisma.QueueSongWhereUniqueInput
  create: Prisma.XOR<Prisma.QueueSongCreateWithoutSongInput, Prisma.QueueSongUncheckedCreateWithoutSongInput>
}

export type QueueSongCreateManySongInputEnvelope = {
  data: Prisma.QueueSongCreateManySongInput | Prisma.QueueSongCreateManySongInput[]
  skipDuplicates?: boolean
}

export type QueueSongUpsertWithWhereUniqueWithoutSongInput = {
  where: Prisma.QueueSongWhereUniqueInput
  update: Prisma.XOR<Prisma.QueueSongUpdateWithoutSongInput, Prisma.QueueSongUncheckedUpdateWithoutSongInput>
  create: Prisma.XOR<Prisma.QueueSongCreateWithoutSongInput, Prisma.QueueSongUncheckedCreateWithoutSongInput>
}

export type QueueSongUpdateWithWhereUniqueWithoutSongInput = {
  where: Prisma.QueueSongWhereUniqueInput
  data: Prisma.XOR<Prisma.QueueSongUpdateWithoutSongInput, Prisma.QueueSongUncheckedUpdateWithoutSongInput>
}

export type QueueSongUpdateManyWithWhereWithoutSongInput = {
  where: Prisma.QueueSongScalarWhereInput
  data: Prisma.XOR<Prisma.QueueSongUpdateManyMutationInput, Prisma.QueueSongUncheckedUpdateManyWithoutSongInput>
}

export type QueueSongCreateManyQueueInput = {
  id?: string
  songId: string
  position: number
}

export type QueueSongUpdateWithoutQueueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  song?: Prisma.SongUpdateOneRequiredWithoutQueueSongsNestedInput
}

export type QueueSongUncheckedUpdateWithoutQueueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type QueueSongUncheckedUpdateManyWithoutQueueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type QueueSongCreateManySongInput = {
  id?: string
  queueId: string
  position: number
}

export type QueueSongUpdateWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  queue?: Prisma.QueueUpdateOneRequiredWithoutSongsNestedInput
}

export type QueueSongUncheckedUpdateWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  queueId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type QueueSongUncheckedUpdateManyWithoutSongInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  queueId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
}



export type QueueSongSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  queueId?: boolean
  songId?: boolean
  position?: boolean
  queue?: boolean | Prisma.QueueDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["queueSong"]>

export type QueueSongSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  queueId?: boolean
  songId?: boolean
  position?: boolean
  queue?: boolean | Prisma.QueueDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["queueSong"]>

export type QueueSongSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  queueId?: boolean
  songId?: boolean
  position?: boolean
  queue?: boolean | Prisma.QueueDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}, ExtArgs["result"]["queueSong"]>

export type QueueSongSelectScalar = {
  id?: boolean
  queueId?: boolean
  songId?: boolean
  position?: boolean
}

export type QueueSongOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "queueId" | "songId" | "position", ExtArgs["result"]["queueSong"]>
export type QueueSongInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  queue?: boolean | Prisma.QueueDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}
export type QueueSongIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  queue?: boolean | Prisma.QueueDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}
export type QueueSongIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  queue?: boolean | Prisma.QueueDefaultArgs<ExtArgs>
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
}

export type $QueueSongPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QueueSong"
  objects: {
    queue: Prisma.$QueuePayload<ExtArgs>
    song: Prisma.$SongPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    queueId: string
    songId: string
    position: number
  }, ExtArgs["result"]["queueSong"]>
  composites: {}
}

export type QueueSongGetPayload<S extends boolean | null | undefined | QueueSongDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QueueSongPayload, S>

export type QueueSongCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QueueSongFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QueueSongCountAggregateInputType | true
  }

export interface QueueSongDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QueueSong'], meta: { name: 'QueueSong' } }
  /**
   * Find zero or one QueueSong that matches the filter.
   * @param {QueueSongFindUniqueArgs} args - Arguments to find a QueueSong
   * @example
   * // Get one QueueSong
   * const queueSong = await prisma.queueSong.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QueueSongFindUniqueArgs>(args: Prisma.SelectSubset<T, QueueSongFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QueueSong that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QueueSongFindUniqueOrThrowArgs} args - Arguments to find a QueueSong
   * @example
   * // Get one QueueSong
   * const queueSong = await prisma.queueSong.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QueueSongFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QueueSongFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QueueSong that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueSongFindFirstArgs} args - Arguments to find a QueueSong
   * @example
   * // Get one QueueSong
   * const queueSong = await prisma.queueSong.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QueueSongFindFirstArgs>(args?: Prisma.SelectSubset<T, QueueSongFindFirstArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QueueSong that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueSongFindFirstOrThrowArgs} args - Arguments to find a QueueSong
   * @example
   * // Get one QueueSong
   * const queueSong = await prisma.queueSong.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QueueSongFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QueueSongFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QueueSongs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueSongFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QueueSongs
   * const queueSongs = await prisma.queueSong.findMany()
   * 
   * // Get first 10 QueueSongs
   * const queueSongs = await prisma.queueSong.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const queueSongWithIdOnly = await prisma.queueSong.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QueueSongFindManyArgs>(args?: Prisma.SelectSubset<T, QueueSongFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QueueSong.
   * @param {QueueSongCreateArgs} args - Arguments to create a QueueSong.
   * @example
   * // Create one QueueSong
   * const QueueSong = await prisma.queueSong.create({
   *   data: {
   *     // ... data to create a QueueSong
   *   }
   * })
   * 
   */
  create<T extends QueueSongCreateArgs>(args: Prisma.SelectSubset<T, QueueSongCreateArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QueueSongs.
   * @param {QueueSongCreateManyArgs} args - Arguments to create many QueueSongs.
   * @example
   * // Create many QueueSongs
   * const queueSong = await prisma.queueSong.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QueueSongCreateManyArgs>(args?: Prisma.SelectSubset<T, QueueSongCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QueueSongs and returns the data saved in the database.
   * @param {QueueSongCreateManyAndReturnArgs} args - Arguments to create many QueueSongs.
   * @example
   * // Create many QueueSongs
   * const queueSong = await prisma.queueSong.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QueueSongs and only return the `id`
   * const queueSongWithIdOnly = await prisma.queueSong.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QueueSongCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QueueSongCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QueueSong.
   * @param {QueueSongDeleteArgs} args - Arguments to delete one QueueSong.
   * @example
   * // Delete one QueueSong
   * const QueueSong = await prisma.queueSong.delete({
   *   where: {
   *     // ... filter to delete one QueueSong
   *   }
   * })
   * 
   */
  delete<T extends QueueSongDeleteArgs>(args: Prisma.SelectSubset<T, QueueSongDeleteArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QueueSong.
   * @param {QueueSongUpdateArgs} args - Arguments to update one QueueSong.
   * @example
   * // Update one QueueSong
   * const queueSong = await prisma.queueSong.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QueueSongUpdateArgs>(args: Prisma.SelectSubset<T, QueueSongUpdateArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QueueSongs.
   * @param {QueueSongDeleteManyArgs} args - Arguments to filter QueueSongs to delete.
   * @example
   * // Delete a few QueueSongs
   * const { count } = await prisma.queueSong.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QueueSongDeleteManyArgs>(args?: Prisma.SelectSubset<T, QueueSongDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QueueSongs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueSongUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QueueSongs
   * const queueSong = await prisma.queueSong.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QueueSongUpdateManyArgs>(args: Prisma.SelectSubset<T, QueueSongUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QueueSongs and returns the data updated in the database.
   * @param {QueueSongUpdateManyAndReturnArgs} args - Arguments to update many QueueSongs.
   * @example
   * // Update many QueueSongs
   * const queueSong = await prisma.queueSong.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QueueSongs and only return the `id`
   * const queueSongWithIdOnly = await prisma.queueSong.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QueueSongUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QueueSongUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QueueSong.
   * @param {QueueSongUpsertArgs} args - Arguments to update or create a QueueSong.
   * @example
   * // Update or create a QueueSong
   * const queueSong = await prisma.queueSong.upsert({
   *   create: {
   *     // ... data to create a QueueSong
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QueueSong we want to update
   *   }
   * })
   */
  upsert<T extends QueueSongUpsertArgs>(args: Prisma.SelectSubset<T, QueueSongUpsertArgs<ExtArgs>>): Prisma.Prisma__QueueSongClient<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QueueSongs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueSongCountArgs} args - Arguments to filter QueueSongs to count.
   * @example
   * // Count the number of QueueSongs
   * const count = await prisma.queueSong.count({
   *   where: {
   *     // ... the filter for the QueueSongs we want to count
   *   }
   * })
  **/
  count<T extends QueueSongCountArgs>(
    args?: Prisma.Subset<T, QueueSongCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QueueSongCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QueueSong.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueSongAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QueueSongAggregateArgs>(args: Prisma.Subset<T, QueueSongAggregateArgs>): Prisma.PrismaPromise<GetQueueSongAggregateType<T>>

  /**
   * Group by QueueSong.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueSongGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QueueSongGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QueueSongGroupByArgs['orderBy'] }
      : { orderBy?: QueueSongGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QueueSongGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQueueSongGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QueueSong model
 */
readonly fields: QueueSongFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QueueSong.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QueueSongClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  queue<T extends Prisma.QueueDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QueueDefaultArgs<ExtArgs>>): Prisma.Prisma__QueueClient<runtime.Types.Result.GetResult<Prisma.$QueuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  song<T extends Prisma.SongDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SongDefaultArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QueueSong model
 */
export interface QueueSongFieldRefs {
  readonly id: Prisma.FieldRef<"QueueSong", 'String'>
  readonly queueId: Prisma.FieldRef<"QueueSong", 'String'>
  readonly songId: Prisma.FieldRef<"QueueSong", 'String'>
  readonly position: Prisma.FieldRef<"QueueSong", 'Int'>
}
    

// Custom InputTypes
/**
 * QueueSong findUnique
 */
export type QueueSongFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * Filter, which QueueSong to fetch.
   */
  where: Prisma.QueueSongWhereUniqueInput
}

/**
 * QueueSong findUniqueOrThrow
 */
export type QueueSongFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * Filter, which QueueSong to fetch.
   */
  where: Prisma.QueueSongWhereUniqueInput
}

/**
 * QueueSong findFirst
 */
export type QueueSongFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * Filter, which QueueSong to fetch.
   */
  where?: Prisma.QueueSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueSongs to fetch.
   */
  orderBy?: Prisma.QueueSongOrderByWithRelationInput | Prisma.QueueSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QueueSongs.
   */
  cursor?: Prisma.QueueSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QueueSongs.
   */
  distinct?: Prisma.QueueSongScalarFieldEnum | Prisma.QueueSongScalarFieldEnum[]
}

/**
 * QueueSong findFirstOrThrow
 */
export type QueueSongFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * Filter, which QueueSong to fetch.
   */
  where?: Prisma.QueueSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueSongs to fetch.
   */
  orderBy?: Prisma.QueueSongOrderByWithRelationInput | Prisma.QueueSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QueueSongs.
   */
  cursor?: Prisma.QueueSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QueueSongs.
   */
  distinct?: Prisma.QueueSongScalarFieldEnum | Prisma.QueueSongScalarFieldEnum[]
}

/**
 * QueueSong findMany
 */
export type QueueSongFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * Filter, which QueueSongs to fetch.
   */
  where?: Prisma.QueueSongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueSongs to fetch.
   */
  orderBy?: Prisma.QueueSongOrderByWithRelationInput | Prisma.QueueSongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QueueSongs.
   */
  cursor?: Prisma.QueueSongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueSongs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueSongs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QueueSongs.
   */
  distinct?: Prisma.QueueSongScalarFieldEnum | Prisma.QueueSongScalarFieldEnum[]
}

/**
 * QueueSong create
 */
export type QueueSongCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * The data needed to create a QueueSong.
   */
  data: Prisma.XOR<Prisma.QueueSongCreateInput, Prisma.QueueSongUncheckedCreateInput>
}

/**
 * QueueSong createMany
 */
export type QueueSongCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QueueSongs.
   */
  data: Prisma.QueueSongCreateManyInput | Prisma.QueueSongCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QueueSong createManyAndReturn
 */
export type QueueSongCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * The data used to create many QueueSongs.
   */
  data: Prisma.QueueSongCreateManyInput | Prisma.QueueSongCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QueueSong update
 */
export type QueueSongUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * The data needed to update a QueueSong.
   */
  data: Prisma.XOR<Prisma.QueueSongUpdateInput, Prisma.QueueSongUncheckedUpdateInput>
  /**
   * Choose, which QueueSong to update.
   */
  where: Prisma.QueueSongWhereUniqueInput
}

/**
 * QueueSong updateMany
 */
export type QueueSongUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QueueSongs.
   */
  data: Prisma.XOR<Prisma.QueueSongUpdateManyMutationInput, Prisma.QueueSongUncheckedUpdateManyInput>
  /**
   * Filter which QueueSongs to update
   */
  where?: Prisma.QueueSongWhereInput
  /**
   * Limit how many QueueSongs to update.
   */
  limit?: number
}

/**
 * QueueSong updateManyAndReturn
 */
export type QueueSongUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * The data used to update QueueSongs.
   */
  data: Prisma.XOR<Prisma.QueueSongUpdateManyMutationInput, Prisma.QueueSongUncheckedUpdateManyInput>
  /**
   * Filter which QueueSongs to update
   */
  where?: Prisma.QueueSongWhereInput
  /**
   * Limit how many QueueSongs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QueueSong upsert
 */
export type QueueSongUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * The filter to search for the QueueSong to update in case it exists.
   */
  where: Prisma.QueueSongWhereUniqueInput
  /**
   * In case the QueueSong found by the `where` argument doesn't exist, create a new QueueSong with this data.
   */
  create: Prisma.XOR<Prisma.QueueSongCreateInput, Prisma.QueueSongUncheckedCreateInput>
  /**
   * In case the QueueSong was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QueueSongUpdateInput, Prisma.QueueSongUncheckedUpdateInput>
}

/**
 * QueueSong delete
 */
export type QueueSongDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  /**
   * Filter which QueueSong to delete.
   */
  where: Prisma.QueueSongWhereUniqueInput
}

/**
 * QueueSong deleteMany
 */
export type QueueSongDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QueueSongs to delete
   */
  where?: Prisma.QueueSongWhereInput
  /**
   * Limit how many QueueSongs to delete.
   */
  limit?: number
}

/**
 * QueueSong without action
 */
export type QueueSongDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
}
