
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SongArtist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SongArtist
 * 
 */
export type SongArtistModel = runtime.Types.Result.DefaultSelection<Prisma.$SongArtistPayload>

export type AggregateSongArtist = {
  _count: SongArtistCountAggregateOutputType | null
  _min: SongArtistMinAggregateOutputType | null
  _max: SongArtistMaxAggregateOutputType | null
}

export type SongArtistMinAggregateOutputType = {
  songId: string | null
  artistId: string | null
}

export type SongArtistMaxAggregateOutputType = {
  songId: string | null
  artistId: string | null
}

export type SongArtistCountAggregateOutputType = {
  songId: number
  artistId: number
  _all: number
}


export type SongArtistMinAggregateInputType = {
  songId?: true
  artistId?: true
}

export type SongArtistMaxAggregateInputType = {
  songId?: true
  artistId?: true
}

export type SongArtistCountAggregateInputType = {
  songId?: true
  artistId?: true
  _all?: true
}

export type SongArtistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SongArtist to aggregate.
   */
  where?: Prisma.SongArtistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SongArtists to fetch.
   */
  orderBy?: Prisma.SongArtistOrderByWithRelationInput | Prisma.SongArtistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SongArtistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SongArtists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SongArtists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SongArtists
  **/
  _count?: true | SongArtistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SongArtistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SongArtistMaxAggregateInputType
}

export type GetSongArtistAggregateType<T extends SongArtistAggregateArgs> = {
      [P in keyof T & keyof AggregateSongArtist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSongArtist[P]>
    : Prisma.GetScalarType<T[P], AggregateSongArtist[P]>
}




export type SongArtistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SongArtistWhereInput
  orderBy?: Prisma.SongArtistOrderByWithAggregationInput | Prisma.SongArtistOrderByWithAggregationInput[]
  by: Prisma.SongArtistScalarFieldEnum[] | Prisma.SongArtistScalarFieldEnum
  having?: Prisma.SongArtistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SongArtistCountAggregateInputType | true
  _min?: SongArtistMinAggregateInputType
  _max?: SongArtistMaxAggregateInputType
}

export type SongArtistGroupByOutputType = {
  songId: string
  artistId: string
  _count: SongArtistCountAggregateOutputType | null
  _min: SongArtistMinAggregateOutputType | null
  _max: SongArtistMaxAggregateOutputType | null
}

export type GetSongArtistGroupByPayload<T extends SongArtistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SongArtistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SongArtistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SongArtistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SongArtistGroupByOutputType[P]>
      }
    >
  >



export type SongArtistWhereInput = {
  AND?: Prisma.SongArtistWhereInput | Prisma.SongArtistWhereInput[]
  OR?: Prisma.SongArtistWhereInput[]
  NOT?: Prisma.SongArtistWhereInput | Prisma.SongArtistWhereInput[]
  songId?: Prisma.StringFilter<"SongArtist"> | string
  artistId?: Prisma.StringFilter<"SongArtist"> | string
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
  artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
}

export type SongArtistOrderByWithRelationInput = {
  songId?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
  song?: Prisma.SongOrderByWithRelationInput
  artist?: Prisma.ArtistOrderByWithRelationInput
}

export type SongArtistWhereUniqueInput = Prisma.AtLeast<{
  songId_artistId?: Prisma.SongArtistSongIdArtistIdCompoundUniqueInput
  AND?: Prisma.SongArtistWhereInput | Prisma.SongArtistWhereInput[]
  OR?: Prisma.SongArtistWhereInput[]
  NOT?: Prisma.SongArtistWhereInput | Prisma.SongArtistWhereInput[]
  songId?: Prisma.StringFilter<"SongArtist"> | string
  artistId?: Prisma.StringFilter<"SongArtist"> | string
  song?: Prisma.XOR<Prisma.SongScalarRelationFilter, Prisma.SongWhereInput>
  artist?: Prisma.XOR<Prisma.ArtistScalarRelationFilter, Prisma.ArtistWhereInput>
}, "songId_artistId">

export type SongArtistOrderByWithAggregationInput = {
  songId?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
  _count?: Prisma.SongArtistCountOrderByAggregateInput
  _max?: Prisma.SongArtistMaxOrderByAggregateInput
  _min?: Prisma.SongArtistMinOrderByAggregateInput
}

export type SongArtistScalarWhereWithAggregatesInput = {
  AND?: Prisma.SongArtistScalarWhereWithAggregatesInput | Prisma.SongArtistScalarWhereWithAggregatesInput[]
  OR?: Prisma.SongArtistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SongArtistScalarWhereWithAggregatesInput | Prisma.SongArtistScalarWhereWithAggregatesInput[]
  songId?: Prisma.StringWithAggregatesFilter<"SongArtist"> | string
  artistId?: Prisma.StringWithAggregatesFilter<"SongArtist"> | string
}

export type SongArtistCreateInput = {
  song: Prisma.SongCreateNestedOneWithoutArtistsInput
  artist: Prisma.ArtistCreateNestedOneWithoutSongsInput
}

export type SongArtistUncheckedCreateInput = {
  songId: string
  artistId: string
}

export type SongArtistUpdateInput = {
  song?: Prisma.SongUpdateOneRequiredWithoutArtistsNestedInput
  artist?: Prisma.ArtistUpdateOneRequiredWithoutSongsNestedInput
}

export type SongArtistUncheckedUpdateInput = {
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  artistId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SongArtistCreateManyInput = {
  songId: string
  artistId: string
}

export type SongArtistUpdateManyMutationInput = {

}

export type SongArtistUncheckedUpdateManyInput = {
  songId?: Prisma.StringFieldUpdateOperationsInput | string
  artistId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SongArtistSongIdArtistIdCompoundUniqueInput = {
  songId: string
  artistId: string
}

export type SongArtistCountOrderByAggregateInput = {
  songId?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
}

export type SongArtistMaxOrderByAggregateInput = {
  songId?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
}

export type SongArtistMinOrderByAggregateInput = {
  songId?: Prisma.SortOrder
  artistId?: Prisma.SortOrder
}

export type SongArtistListRelationFilter = {
  every?: Prisma.SongArtistWhereInput
  some?: Prisma.SongArtistWhereInput
  none?: Prisma.SongArtistWhereInput
}

export type SongArtistOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SongArtistCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutSongInput, Prisma.SongArtistUncheckedCreateWithoutSongInput> | Prisma.SongArtistCreateWithoutSongInput[] | Prisma.SongArtistUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutSongInput | Prisma.SongArtistCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.SongArtistCreateManySongInputEnvelope
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
}

export type SongArtistUncheckedCreateNestedManyWithoutSongInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutSongInput, Prisma.SongArtistUncheckedCreateWithoutSongInput> | Prisma.SongArtistCreateWithoutSongInput[] | Prisma.SongArtistUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutSongInput | Prisma.SongArtistCreateOrConnectWithoutSongInput[]
  createMany?: Prisma.SongArtistCreateManySongInputEnvelope
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
}

export type SongArtistUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutSongInput, Prisma.SongArtistUncheckedCreateWithoutSongInput> | Prisma.SongArtistCreateWithoutSongInput[] | Prisma.SongArtistUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutSongInput | Prisma.SongArtistCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.SongArtistUpsertWithWhereUniqueWithoutSongInput | Prisma.SongArtistUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.SongArtistCreateManySongInputEnvelope
  set?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  disconnect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  delete?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  update?: Prisma.SongArtistUpdateWithWhereUniqueWithoutSongInput | Prisma.SongArtistUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.SongArtistUpdateManyWithWhereWithoutSongInput | Prisma.SongArtistUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.SongArtistScalarWhereInput | Prisma.SongArtistScalarWhereInput[]
}

export type SongArtistUncheckedUpdateManyWithoutSongNestedInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutSongInput, Prisma.SongArtistUncheckedCreateWithoutSongInput> | Prisma.SongArtistCreateWithoutSongInput[] | Prisma.SongArtistUncheckedCreateWithoutSongInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutSongInput | Prisma.SongArtistCreateOrConnectWithoutSongInput[]
  upsert?: Prisma.SongArtistUpsertWithWhereUniqueWithoutSongInput | Prisma.SongArtistUpsertWithWhereUniqueWithoutSongInput[]
  createMany?: Prisma.SongArtistCreateManySongInputEnvelope
  set?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  disconnect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  delete?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  update?: Prisma.SongArtistUpdateWithWhereUniqueWithoutSongInput | Prisma.SongArtistUpdateWithWhereUniqueWithoutSongInput[]
  updateMany?: Prisma.SongArtistUpdateManyWithWhereWithoutSongInput | Prisma.SongArtistUpdateManyWithWhereWithoutSongInput[]
  deleteMany?: Prisma.SongArtistScalarWhereInput | Prisma.SongArtistScalarWhereInput[]
}

export type SongArtistCreateNestedManyWithoutArtistInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutArtistInput, Prisma.SongArtistUncheckedCreateWithoutArtistInput> | Prisma.SongArtistCreateWithoutArtistInput[] | Prisma.SongArtistUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutArtistInput | Prisma.SongArtistCreateOrConnectWithoutArtistInput[]
  createMany?: Prisma.SongArtistCreateManyArtistInputEnvelope
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
}

export type SongArtistUncheckedCreateNestedManyWithoutArtistInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutArtistInput, Prisma.SongArtistUncheckedCreateWithoutArtistInput> | Prisma.SongArtistCreateWithoutArtistInput[] | Prisma.SongArtistUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutArtistInput | Prisma.SongArtistCreateOrConnectWithoutArtistInput[]
  createMany?: Prisma.SongArtistCreateManyArtistInputEnvelope
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
}

export type SongArtistUpdateManyWithoutArtistNestedInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutArtistInput, Prisma.SongArtistUncheckedCreateWithoutArtistInput> | Prisma.SongArtistCreateWithoutArtistInput[] | Prisma.SongArtistUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutArtistInput | Prisma.SongArtistCreateOrConnectWithoutArtistInput[]
  upsert?: Prisma.SongArtistUpsertWithWhereUniqueWithoutArtistInput | Prisma.SongArtistUpsertWithWhereUniqueWithoutArtistInput[]
  createMany?: Prisma.SongArtistCreateManyArtistInputEnvelope
  set?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  disconnect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  delete?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  update?: Prisma.SongArtistUpdateWithWhereUniqueWithoutArtistInput | Prisma.SongArtistUpdateWithWhereUniqueWithoutArtistInput[]
  updateMany?: Prisma.SongArtistUpdateManyWithWhereWithoutArtistInput | Prisma.SongArtistUpdateManyWithWhereWithoutArtistInput[]
  deleteMany?: Prisma.SongArtistScalarWhereInput | Prisma.SongArtistScalarWhereInput[]
}

export type SongArtistUncheckedUpdateManyWithoutArtistNestedInput = {
  create?: Prisma.XOR<Prisma.SongArtistCreateWithoutArtistInput, Prisma.SongArtistUncheckedCreateWithoutArtistInput> | Prisma.SongArtistCreateWithoutArtistInput[] | Prisma.SongArtistUncheckedCreateWithoutArtistInput[]
  connectOrCreate?: Prisma.SongArtistCreateOrConnectWithoutArtistInput | Prisma.SongArtistCreateOrConnectWithoutArtistInput[]
  upsert?: Prisma.SongArtistUpsertWithWhereUniqueWithoutArtistInput | Prisma.SongArtistUpsertWithWhereUniqueWithoutArtistInput[]
  createMany?: Prisma.SongArtistCreateManyArtistInputEnvelope
  set?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  disconnect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  delete?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  connect?: Prisma.SongArtistWhereUniqueInput | Prisma.SongArtistWhereUniqueInput[]
  update?: Prisma.SongArtistUpdateWithWhereUniqueWithoutArtistInput | Prisma.SongArtistUpdateWithWhereUniqueWithoutArtistInput[]
  updateMany?: Prisma.SongArtistUpdateManyWithWhereWithoutArtistInput | Prisma.SongArtistUpdateManyWithWhereWithoutArtistInput[]
  deleteMany?: Prisma.SongArtistScalarWhereInput | Prisma.SongArtistScalarWhereInput[]
}

export type SongArtistCreateWithoutSongInput = {
  artist: Prisma.ArtistCreateNestedOneWithoutSongsInput
}

export type SongArtistUncheckedCreateWithoutSongInput = {
  artistId: string
}

export type SongArtistCreateOrConnectWithoutSongInput = {
  where: Prisma.SongArtistWhereUniqueInput
  create: Prisma.XOR<Prisma.SongArtistCreateWithoutSongInput, Prisma.SongArtistUncheckedCreateWithoutSongInput>
}

export type SongArtistCreateManySongInputEnvelope = {
  data: Prisma.SongArtistCreateManySongInput | Prisma.SongArtistCreateManySongInput[]
  skipDuplicates?: boolean
}

export type SongArtistUpsertWithWhereUniqueWithoutSongInput = {
  where: Prisma.SongArtistWhereUniqueInput
  update: Prisma.XOR<Prisma.SongArtistUpdateWithoutSongInput, Prisma.SongArtistUncheckedUpdateWithoutSongInput>
  create: Prisma.XOR<Prisma.SongArtistCreateWithoutSongInput, Prisma.SongArtistUncheckedCreateWithoutSongInput>
}

export type SongArtistUpdateWithWhereUniqueWithoutSongInput = {
  where: Prisma.SongArtistWhereUniqueInput
  data: Prisma.XOR<Prisma.SongArtistUpdateWithoutSongInput, Prisma.SongArtistUncheckedUpdateWithoutSongInput>
}

export type SongArtistUpdateManyWithWhereWithoutSongInput = {
  where: Prisma.SongArtistScalarWhereInput
  data: Prisma.XOR<Prisma.SongArtistUpdateManyMutationInput, Prisma.SongArtistUncheckedUpdateManyWithoutSongInput>
}

export type SongArtistScalarWhereInput = {
  AND?: Prisma.SongArtistScalarWhereInput | Prisma.SongArtistScalarWhereInput[]
  OR?: Prisma.SongArtistScalarWhereInput[]
  NOT?: Prisma.SongArtistScalarWhereInput | Prisma.SongArtistScalarWhereInput[]
  songId?: Prisma.StringFilter<"SongArtist"> | string
  artistId?: Prisma.StringFilter<"SongArtist"> | string
}

export type SongArtistCreateWithoutArtistInput = {
  song: Prisma.SongCreateNestedOneWithoutArtistsInput
}

export type SongArtistUncheckedCreateWithoutArtistInput = {
  songId: string
}

export type SongArtistCreateOrConnectWithoutArtistInput = {
  where: Prisma.SongArtistWhereUniqueInput
  create: Prisma.XOR<Prisma.SongArtistCreateWithoutArtistInput, Prisma.SongArtistUncheckedCreateWithoutArtistInput>
}

export type SongArtistCreateManyArtistInputEnvelope = {
  data: Prisma.SongArtistCreateManyArtistInput | Prisma.SongArtistCreateManyArtistInput[]
  skipDuplicates?: boolean
}

export type SongArtistUpsertWithWhereUniqueWithoutArtistInput = {
  where: Prisma.SongArtistWhereUniqueInput
  update: Prisma.XOR<Prisma.SongArtistUpdateWithoutArtistInput, Prisma.SongArtistUncheckedUpdateWithoutArtistInput>
  create: Prisma.XOR<Prisma.SongArtistCreateWithoutArtistInput, Prisma.SongArtistUncheckedCreateWithoutArtistInput>
}

export type SongArtistUpdateWithWhereUniqueWithoutArtistInput = {
  where: Prisma.SongArtistWhereUniqueInput
  data: Prisma.XOR<Prisma.SongArtistUpdateWithoutArtistInput, Prisma.SongArtistUncheckedUpdateWithoutArtistInput>
}

export type SongArtistUpdateManyWithWhereWithoutArtistInput = {
  where: Prisma.SongArtistScalarWhereInput
  data: Prisma.XOR<Prisma.SongArtistUpdateManyMutationInput, Prisma.SongArtistUncheckedUpdateManyWithoutArtistInput>
}

export type SongArtistCreateManySongInput = {
  artistId: string
}

export type SongArtistUpdateWithoutSongInput = {
  artist?: Prisma.ArtistUpdateOneRequiredWithoutSongsNestedInput
}

export type SongArtistUncheckedUpdateWithoutSongInput = {
  artistId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SongArtistUncheckedUpdateManyWithoutSongInput = {
  artistId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SongArtistCreateManyArtistInput = {
  songId: string
}

export type SongArtistUpdateWithoutArtistInput = {
  song?: Prisma.SongUpdateOneRequiredWithoutArtistsNestedInput
}

export type SongArtistUncheckedUpdateWithoutArtistInput = {
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SongArtistUncheckedUpdateManyWithoutArtistInput = {
  songId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SongArtistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  songId?: boolean
  artistId?: boolean
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["songArtist"]>

export type SongArtistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  songId?: boolean
  artistId?: boolean
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["songArtist"]>

export type SongArtistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  songId?: boolean
  artistId?: boolean
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["songArtist"]>

export type SongArtistSelectScalar = {
  songId?: boolean
  artistId?: boolean
}

export type SongArtistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"songId" | "artistId", ExtArgs["result"]["songArtist"]>
export type SongArtistInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}
export type SongArtistIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}
export type SongArtistIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  song?: boolean | Prisma.SongDefaultArgs<ExtArgs>
  artist?: boolean | Prisma.ArtistDefaultArgs<ExtArgs>
}

export type $SongArtistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SongArtist"
  objects: {
    song: Prisma.$SongPayload<ExtArgs>
    artist: Prisma.$ArtistPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    songId: string
    artistId: string
  }, ExtArgs["result"]["songArtist"]>
  composites: {}
}

export type SongArtistGetPayload<S extends boolean | null | undefined | SongArtistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SongArtistPayload, S>

export type SongArtistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SongArtistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SongArtistCountAggregateInputType | true
  }

export interface SongArtistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SongArtist'], meta: { name: 'SongArtist' } }
  /**
   * Find zero or one SongArtist that matches the filter.
   * @param {SongArtistFindUniqueArgs} args - Arguments to find a SongArtist
   * @example
   * // Get one SongArtist
   * const songArtist = await prisma.songArtist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SongArtistFindUniqueArgs>(args: Prisma.SelectSubset<T, SongArtistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SongArtist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SongArtistFindUniqueOrThrowArgs} args - Arguments to find a SongArtist
   * @example
   * // Get one SongArtist
   * const songArtist = await prisma.songArtist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SongArtistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SongArtistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SongArtist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongArtistFindFirstArgs} args - Arguments to find a SongArtist
   * @example
   * // Get one SongArtist
   * const songArtist = await prisma.songArtist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SongArtistFindFirstArgs>(args?: Prisma.SelectSubset<T, SongArtistFindFirstArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SongArtist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongArtistFindFirstOrThrowArgs} args - Arguments to find a SongArtist
   * @example
   * // Get one SongArtist
   * const songArtist = await prisma.songArtist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SongArtistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SongArtistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SongArtists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongArtistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SongArtists
   * const songArtists = await prisma.songArtist.findMany()
   * 
   * // Get first 10 SongArtists
   * const songArtists = await prisma.songArtist.findMany({ take: 10 })
   * 
   * // Only select the `songId`
   * const songArtistWithSongIdOnly = await prisma.songArtist.findMany({ select: { songId: true } })
   * 
   */
  findMany<T extends SongArtistFindManyArgs>(args?: Prisma.SelectSubset<T, SongArtistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SongArtist.
   * @param {SongArtistCreateArgs} args - Arguments to create a SongArtist.
   * @example
   * // Create one SongArtist
   * const SongArtist = await prisma.songArtist.create({
   *   data: {
   *     // ... data to create a SongArtist
   *   }
   * })
   * 
   */
  create<T extends SongArtistCreateArgs>(args: Prisma.SelectSubset<T, SongArtistCreateArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SongArtists.
   * @param {SongArtistCreateManyArgs} args - Arguments to create many SongArtists.
   * @example
   * // Create many SongArtists
   * const songArtist = await prisma.songArtist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SongArtistCreateManyArgs>(args?: Prisma.SelectSubset<T, SongArtistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SongArtists and returns the data saved in the database.
   * @param {SongArtistCreateManyAndReturnArgs} args - Arguments to create many SongArtists.
   * @example
   * // Create many SongArtists
   * const songArtist = await prisma.songArtist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SongArtists and only return the `songId`
   * const songArtistWithSongIdOnly = await prisma.songArtist.createManyAndReturn({
   *   select: { songId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SongArtistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SongArtistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SongArtist.
   * @param {SongArtistDeleteArgs} args - Arguments to delete one SongArtist.
   * @example
   * // Delete one SongArtist
   * const SongArtist = await prisma.songArtist.delete({
   *   where: {
   *     // ... filter to delete one SongArtist
   *   }
   * })
   * 
   */
  delete<T extends SongArtistDeleteArgs>(args: Prisma.SelectSubset<T, SongArtistDeleteArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SongArtist.
   * @param {SongArtistUpdateArgs} args - Arguments to update one SongArtist.
   * @example
   * // Update one SongArtist
   * const songArtist = await prisma.songArtist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SongArtistUpdateArgs>(args: Prisma.SelectSubset<T, SongArtistUpdateArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SongArtists.
   * @param {SongArtistDeleteManyArgs} args - Arguments to filter SongArtists to delete.
   * @example
   * // Delete a few SongArtists
   * const { count } = await prisma.songArtist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SongArtistDeleteManyArgs>(args?: Prisma.SelectSubset<T, SongArtistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SongArtists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongArtistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SongArtists
   * const songArtist = await prisma.songArtist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SongArtistUpdateManyArgs>(args: Prisma.SelectSubset<T, SongArtistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SongArtists and returns the data updated in the database.
   * @param {SongArtistUpdateManyAndReturnArgs} args - Arguments to update many SongArtists.
   * @example
   * // Update many SongArtists
   * const songArtist = await prisma.songArtist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SongArtists and only return the `songId`
   * const songArtistWithSongIdOnly = await prisma.songArtist.updateManyAndReturn({
   *   select: { songId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SongArtistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SongArtistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SongArtist.
   * @param {SongArtistUpsertArgs} args - Arguments to update or create a SongArtist.
   * @example
   * // Update or create a SongArtist
   * const songArtist = await prisma.songArtist.upsert({
   *   create: {
   *     // ... data to create a SongArtist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SongArtist we want to update
   *   }
   * })
   */
  upsert<T extends SongArtistUpsertArgs>(args: Prisma.SelectSubset<T, SongArtistUpsertArgs<ExtArgs>>): Prisma.Prisma__SongArtistClient<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SongArtists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongArtistCountArgs} args - Arguments to filter SongArtists to count.
   * @example
   * // Count the number of SongArtists
   * const count = await prisma.songArtist.count({
   *   where: {
   *     // ... the filter for the SongArtists we want to count
   *   }
   * })
  **/
  count<T extends SongArtistCountArgs>(
    args?: Prisma.Subset<T, SongArtistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SongArtistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SongArtist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongArtistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SongArtistAggregateArgs>(args: Prisma.Subset<T, SongArtistAggregateArgs>): Prisma.PrismaPromise<GetSongArtistAggregateType<T>>

  /**
   * Group by SongArtist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongArtistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SongArtistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SongArtistGroupByArgs['orderBy'] }
      : { orderBy?: SongArtistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SongArtistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSongArtistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SongArtist model
 */
readonly fields: SongArtistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SongArtist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SongArtistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  song<T extends Prisma.SongDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SongDefaultArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  artist<T extends Prisma.ArtistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ArtistDefaultArgs<ExtArgs>>): Prisma.Prisma__ArtistClient<runtime.Types.Result.GetResult<Prisma.$ArtistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SongArtist model
 */
export interface SongArtistFieldRefs {
  readonly songId: Prisma.FieldRef<"SongArtist", 'String'>
  readonly artistId: Prisma.FieldRef<"SongArtist", 'String'>
}
    

// Custom InputTypes
/**
 * SongArtist findUnique
 */
export type SongArtistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * Filter, which SongArtist to fetch.
   */
  where: Prisma.SongArtistWhereUniqueInput
}

/**
 * SongArtist findUniqueOrThrow
 */
export type SongArtistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * Filter, which SongArtist to fetch.
   */
  where: Prisma.SongArtistWhereUniqueInput
}

/**
 * SongArtist findFirst
 */
export type SongArtistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * Filter, which SongArtist to fetch.
   */
  where?: Prisma.SongArtistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SongArtists to fetch.
   */
  orderBy?: Prisma.SongArtistOrderByWithRelationInput | Prisma.SongArtistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SongArtists.
   */
  cursor?: Prisma.SongArtistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SongArtists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SongArtists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SongArtists.
   */
  distinct?: Prisma.SongArtistScalarFieldEnum | Prisma.SongArtistScalarFieldEnum[]
}

/**
 * SongArtist findFirstOrThrow
 */
export type SongArtistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * Filter, which SongArtist to fetch.
   */
  where?: Prisma.SongArtistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SongArtists to fetch.
   */
  orderBy?: Prisma.SongArtistOrderByWithRelationInput | Prisma.SongArtistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SongArtists.
   */
  cursor?: Prisma.SongArtistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SongArtists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SongArtists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SongArtists.
   */
  distinct?: Prisma.SongArtistScalarFieldEnum | Prisma.SongArtistScalarFieldEnum[]
}

/**
 * SongArtist findMany
 */
export type SongArtistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * Filter, which SongArtists to fetch.
   */
  where?: Prisma.SongArtistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SongArtists to fetch.
   */
  orderBy?: Prisma.SongArtistOrderByWithRelationInput | Prisma.SongArtistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SongArtists.
   */
  cursor?: Prisma.SongArtistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SongArtists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SongArtists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SongArtists.
   */
  distinct?: Prisma.SongArtistScalarFieldEnum | Prisma.SongArtistScalarFieldEnum[]
}

/**
 * SongArtist create
 */
export type SongArtistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * The data needed to create a SongArtist.
   */
  data: Prisma.XOR<Prisma.SongArtistCreateInput, Prisma.SongArtistUncheckedCreateInput>
}

/**
 * SongArtist createMany
 */
export type SongArtistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SongArtists.
   */
  data: Prisma.SongArtistCreateManyInput | Prisma.SongArtistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SongArtist createManyAndReturn
 */
export type SongArtistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * The data used to create many SongArtists.
   */
  data: Prisma.SongArtistCreateManyInput | Prisma.SongArtistCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SongArtist update
 */
export type SongArtistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * The data needed to update a SongArtist.
   */
  data: Prisma.XOR<Prisma.SongArtistUpdateInput, Prisma.SongArtistUncheckedUpdateInput>
  /**
   * Choose, which SongArtist to update.
   */
  where: Prisma.SongArtistWhereUniqueInput
}

/**
 * SongArtist updateMany
 */
export type SongArtistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SongArtists.
   */
  data: Prisma.XOR<Prisma.SongArtistUpdateManyMutationInput, Prisma.SongArtistUncheckedUpdateManyInput>
  /**
   * Filter which SongArtists to update
   */
  where?: Prisma.SongArtistWhereInput
  /**
   * Limit how many SongArtists to update.
   */
  limit?: number
}

/**
 * SongArtist updateManyAndReturn
 */
export type SongArtistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * The data used to update SongArtists.
   */
  data: Prisma.XOR<Prisma.SongArtistUpdateManyMutationInput, Prisma.SongArtistUncheckedUpdateManyInput>
  /**
   * Filter which SongArtists to update
   */
  where?: Prisma.SongArtistWhereInput
  /**
   * Limit how many SongArtists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SongArtist upsert
 */
export type SongArtistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * The filter to search for the SongArtist to update in case it exists.
   */
  where: Prisma.SongArtistWhereUniqueInput
  /**
   * In case the SongArtist found by the `where` argument doesn't exist, create a new SongArtist with this data.
   */
  create: Prisma.XOR<Prisma.SongArtistCreateInput, Prisma.SongArtistUncheckedCreateInput>
  /**
   * In case the SongArtist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SongArtistUpdateInput, Prisma.SongArtistUncheckedUpdateInput>
}

/**
 * SongArtist delete
 */
export type SongArtistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  /**
   * Filter which SongArtist to delete.
   */
  where: Prisma.SongArtistWhereUniqueInput
}

/**
 * SongArtist deleteMany
 */
export type SongArtistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SongArtists to delete
   */
  where?: Prisma.SongArtistWhereInput
  /**
   * Limit how many SongArtists to delete.
   */
  limit?: number
}

/**
 * SongArtist without action
 */
export type SongArtistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
}
