
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Song` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Song
 * 
 */
export type SongModel = runtime.Types.Result.DefaultSelection<Prisma.$SongPayload>

export type AggregateSong = {
  _count: SongCountAggregateOutputType | null
  _avg: SongAvgAggregateOutputType | null
  _sum: SongSumAggregateOutputType | null
  _min: SongMinAggregateOutputType | null
  _max: SongMaxAggregateOutputType | null
}

export type SongAvgAggregateOutputType = {
  duration: number | null
}

export type SongSumAggregateOutputType = {
  duration: number | null
}

export type SongMinAggregateOutputType = {
  id: string | null
  title: string | null
  fileName: string | null
  duration: number | null
  albumId: string | null
  image: string | null
  plainLyrics: string | null
  syncedLyrics: string | null
}

export type SongMaxAggregateOutputType = {
  id: string | null
  title: string | null
  fileName: string | null
  duration: number | null
  albumId: string | null
  image: string | null
  plainLyrics: string | null
  syncedLyrics: string | null
}

export type SongCountAggregateOutputType = {
  id: number
  title: number
  fileName: number
  duration: number
  albumId: number
  image: number
  plainLyrics: number
  syncedLyrics: number
  _all: number
}


export type SongAvgAggregateInputType = {
  duration?: true
}

export type SongSumAggregateInputType = {
  duration?: true
}

export type SongMinAggregateInputType = {
  id?: true
  title?: true
  fileName?: true
  duration?: true
  albumId?: true
  image?: true
  plainLyrics?: true
  syncedLyrics?: true
}

export type SongMaxAggregateInputType = {
  id?: true
  title?: true
  fileName?: true
  duration?: true
  albumId?: true
  image?: true
  plainLyrics?: true
  syncedLyrics?: true
}

export type SongCountAggregateInputType = {
  id?: true
  title?: true
  fileName?: true
  duration?: true
  albumId?: true
  image?: true
  plainLyrics?: true
  syncedLyrics?: true
  _all?: true
}

export type SongAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Song to aggregate.
   */
  where?: Prisma.SongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Songs to fetch.
   */
  orderBy?: Prisma.SongOrderByWithRelationInput | Prisma.SongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Songs
  **/
  _count?: true | SongCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SongAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SongSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SongMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SongMaxAggregateInputType
}

export type GetSongAggregateType<T extends SongAggregateArgs> = {
      [P in keyof T & keyof AggregateSong]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSong[P]>
    : Prisma.GetScalarType<T[P], AggregateSong[P]>
}




export type SongGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SongWhereInput
  orderBy?: Prisma.SongOrderByWithAggregationInput | Prisma.SongOrderByWithAggregationInput[]
  by: Prisma.SongScalarFieldEnum[] | Prisma.SongScalarFieldEnum
  having?: Prisma.SongScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SongCountAggregateInputType | true
  _avg?: SongAvgAggregateInputType
  _sum?: SongSumAggregateInputType
  _min?: SongMinAggregateInputType
  _max?: SongMaxAggregateInputType
}

export type SongGroupByOutputType = {
  id: string
  title: string
  fileName: string
  duration: number
  albumId: string | null
  image: string
  plainLyrics: string
  syncedLyrics: string
  _count: SongCountAggregateOutputType | null
  _avg: SongAvgAggregateOutputType | null
  _sum: SongSumAggregateOutputType | null
  _min: SongMinAggregateOutputType | null
  _max: SongMaxAggregateOutputType | null
}

export type GetSongGroupByPayload<T extends SongGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SongGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SongGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SongGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SongGroupByOutputType[P]>
      }
    >
  >



export type SongWhereInput = {
  AND?: Prisma.SongWhereInput | Prisma.SongWhereInput[]
  OR?: Prisma.SongWhereInput[]
  NOT?: Prisma.SongWhereInput | Prisma.SongWhereInput[]
  id?: Prisma.StringFilter<"Song"> | string
  title?: Prisma.StringFilter<"Song"> | string
  fileName?: Prisma.StringFilter<"Song"> | string
  duration?: Prisma.IntFilter<"Song"> | number
  albumId?: Prisma.StringNullableFilter<"Song"> | string | null
  image?: Prisma.StringFilter<"Song"> | string
  plainLyrics?: Prisma.StringFilter<"Song"> | string
  syncedLyrics?: Prisma.StringFilter<"Song"> | string
  artists?: Prisma.SongArtistListRelationFilter
  playlistSongs?: Prisma.PlaylistSongListRelationFilter
  album?: Prisma.XOR<Prisma.AlbumNullableScalarRelationFilter, Prisma.AlbumWhereInput> | null
  queueSongs?: Prisma.QueueSongListRelationFilter
}

export type SongOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  albumId?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrder
  plainLyrics?: Prisma.SortOrder
  syncedLyrics?: Prisma.SortOrder
  artists?: Prisma.SongArtistOrderByRelationAggregateInput
  playlistSongs?: Prisma.PlaylistSongOrderByRelationAggregateInput
  album?: Prisma.AlbumOrderByWithRelationInput
  queueSongs?: Prisma.QueueSongOrderByRelationAggregateInput
}

export type SongWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SongWhereInput | Prisma.SongWhereInput[]
  OR?: Prisma.SongWhereInput[]
  NOT?: Prisma.SongWhereInput | Prisma.SongWhereInput[]
  title?: Prisma.StringFilter<"Song"> | string
  fileName?: Prisma.StringFilter<"Song"> | string
  duration?: Prisma.IntFilter<"Song"> | number
  albumId?: Prisma.StringNullableFilter<"Song"> | string | null
  image?: Prisma.StringFilter<"Song"> | string
  plainLyrics?: Prisma.StringFilter<"Song"> | string
  syncedLyrics?: Prisma.StringFilter<"Song"> | string
  artists?: Prisma.SongArtistListRelationFilter
  playlistSongs?: Prisma.PlaylistSongListRelationFilter
  album?: Prisma.XOR<Prisma.AlbumNullableScalarRelationFilter, Prisma.AlbumWhereInput> | null
  queueSongs?: Prisma.QueueSongListRelationFilter
}, "id">

export type SongOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  albumId?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrder
  plainLyrics?: Prisma.SortOrder
  syncedLyrics?: Prisma.SortOrder
  _count?: Prisma.SongCountOrderByAggregateInput
  _avg?: Prisma.SongAvgOrderByAggregateInput
  _max?: Prisma.SongMaxOrderByAggregateInput
  _min?: Prisma.SongMinOrderByAggregateInput
  _sum?: Prisma.SongSumOrderByAggregateInput
}

export type SongScalarWhereWithAggregatesInput = {
  AND?: Prisma.SongScalarWhereWithAggregatesInput | Prisma.SongScalarWhereWithAggregatesInput[]
  OR?: Prisma.SongScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SongScalarWhereWithAggregatesInput | Prisma.SongScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Song"> | string
  title?: Prisma.StringWithAggregatesFilter<"Song"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"Song"> | string
  duration?: Prisma.IntWithAggregatesFilter<"Song"> | number
  albumId?: Prisma.StringNullableWithAggregatesFilter<"Song"> | string | null
  image?: Prisma.StringWithAggregatesFilter<"Song"> | string
  plainLyrics?: Prisma.StringWithAggregatesFilter<"Song"> | string
  syncedLyrics?: Prisma.StringWithAggregatesFilter<"Song"> | string
}

export type SongCreateInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistCreateNestedManyWithoutSongInput
  playlistSongs?: Prisma.PlaylistSongCreateNestedManyWithoutSongInput
  album?: Prisma.AlbumCreateNestedOneWithoutSongsInput
  queueSongs?: Prisma.QueueSongCreateNestedManyWithoutSongInput
}

export type SongUncheckedCreateInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  albumId?: string | null
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistUncheckedCreateNestedManyWithoutSongInput
  playlistSongs?: Prisma.PlaylistSongUncheckedCreateNestedManyWithoutSongInput
  queueSongs?: Prisma.QueueSongUncheckedCreateNestedManyWithoutSongInput
}

export type SongUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUpdateManyWithoutSongNestedInput
  playlistSongs?: Prisma.PlaylistSongUpdateManyWithoutSongNestedInput
  album?: Prisma.AlbumUpdateOneWithoutSongsNestedInput
  queueSongs?: Prisma.QueueSongUpdateManyWithoutSongNestedInput
}

export type SongUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  albumId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUncheckedUpdateManyWithoutSongNestedInput
  playlistSongs?: Prisma.PlaylistSongUncheckedUpdateManyWithoutSongNestedInput
  queueSongs?: Prisma.QueueSongUncheckedUpdateManyWithoutSongNestedInput
}

export type SongCreateManyInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  albumId?: string | null
  image: string
  plainLyrics: string
  syncedLyrics: string
}

export type SongUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SongUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  albumId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SongScalarRelationFilter = {
  is?: Prisma.SongWhereInput
  isNot?: Prisma.SongWhereInput
}

export type SongCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  albumId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  plainLyrics?: Prisma.SortOrder
  syncedLyrics?: Prisma.SortOrder
}

export type SongAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type SongMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  albumId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  plainLyrics?: Prisma.SortOrder
  syncedLyrics?: Prisma.SortOrder
}

export type SongMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  albumId?: Prisma.SortOrder
  image?: Prisma.SortOrder
  plainLyrics?: Prisma.SortOrder
  syncedLyrics?: Prisma.SortOrder
}

export type SongSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type SongListRelationFilter = {
  every?: Prisma.SongWhereInput
  some?: Prisma.SongWhereInput
  none?: Prisma.SongWhereInput
}

export type SongOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SongCreateNestedOneWithoutArtistsInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutArtistsInput, Prisma.SongUncheckedCreateWithoutArtistsInput>
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutArtistsInput
  connect?: Prisma.SongWhereUniqueInput
}

export type SongUpdateOneRequiredWithoutArtistsNestedInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutArtistsInput, Prisma.SongUncheckedCreateWithoutArtistsInput>
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutArtistsInput
  upsert?: Prisma.SongUpsertWithoutArtistsInput
  connect?: Prisma.SongWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SongUpdateToOneWithWhereWithoutArtistsInput, Prisma.SongUpdateWithoutArtistsInput>, Prisma.SongUncheckedUpdateWithoutArtistsInput>
}

export type SongCreateNestedOneWithoutPlaylistSongsInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutPlaylistSongsInput, Prisma.SongUncheckedCreateWithoutPlaylistSongsInput>
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutPlaylistSongsInput
  connect?: Prisma.SongWhereUniqueInput
}

export type SongUpdateOneRequiredWithoutPlaylistSongsNestedInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutPlaylistSongsInput, Prisma.SongUncheckedCreateWithoutPlaylistSongsInput>
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutPlaylistSongsInput
  upsert?: Prisma.SongUpsertWithoutPlaylistSongsInput
  connect?: Prisma.SongWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SongUpdateToOneWithWhereWithoutPlaylistSongsInput, Prisma.SongUpdateWithoutPlaylistSongsInput>, Prisma.SongUncheckedUpdateWithoutPlaylistSongsInput>
}

export type SongCreateNestedOneWithoutQueueSongsInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutQueueSongsInput, Prisma.SongUncheckedCreateWithoutQueueSongsInput>
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutQueueSongsInput
  connect?: Prisma.SongWhereUniqueInput
}

export type SongUpdateOneRequiredWithoutQueueSongsNestedInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutQueueSongsInput, Prisma.SongUncheckedCreateWithoutQueueSongsInput>
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutQueueSongsInput
  upsert?: Prisma.SongUpsertWithoutQueueSongsInput
  connect?: Prisma.SongWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SongUpdateToOneWithWhereWithoutQueueSongsInput, Prisma.SongUpdateWithoutQueueSongsInput>, Prisma.SongUncheckedUpdateWithoutQueueSongsInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type SongCreateNestedManyWithoutAlbumInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutAlbumInput, Prisma.SongUncheckedCreateWithoutAlbumInput> | Prisma.SongCreateWithoutAlbumInput[] | Prisma.SongUncheckedCreateWithoutAlbumInput[]
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutAlbumInput | Prisma.SongCreateOrConnectWithoutAlbumInput[]
  createMany?: Prisma.SongCreateManyAlbumInputEnvelope
  connect?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
}

export type SongUncheckedCreateNestedManyWithoutAlbumInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutAlbumInput, Prisma.SongUncheckedCreateWithoutAlbumInput> | Prisma.SongCreateWithoutAlbumInput[] | Prisma.SongUncheckedCreateWithoutAlbumInput[]
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutAlbumInput | Prisma.SongCreateOrConnectWithoutAlbumInput[]
  createMany?: Prisma.SongCreateManyAlbumInputEnvelope
  connect?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
}

export type SongUpdateManyWithoutAlbumNestedInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutAlbumInput, Prisma.SongUncheckedCreateWithoutAlbumInput> | Prisma.SongCreateWithoutAlbumInput[] | Prisma.SongUncheckedCreateWithoutAlbumInput[]
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutAlbumInput | Prisma.SongCreateOrConnectWithoutAlbumInput[]
  upsert?: Prisma.SongUpsertWithWhereUniqueWithoutAlbumInput | Prisma.SongUpsertWithWhereUniqueWithoutAlbumInput[]
  createMany?: Prisma.SongCreateManyAlbumInputEnvelope
  set?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  disconnect?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  delete?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  connect?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  update?: Prisma.SongUpdateWithWhereUniqueWithoutAlbumInput | Prisma.SongUpdateWithWhereUniqueWithoutAlbumInput[]
  updateMany?: Prisma.SongUpdateManyWithWhereWithoutAlbumInput | Prisma.SongUpdateManyWithWhereWithoutAlbumInput[]
  deleteMany?: Prisma.SongScalarWhereInput | Prisma.SongScalarWhereInput[]
}

export type SongUncheckedUpdateManyWithoutAlbumNestedInput = {
  create?: Prisma.XOR<Prisma.SongCreateWithoutAlbumInput, Prisma.SongUncheckedCreateWithoutAlbumInput> | Prisma.SongCreateWithoutAlbumInput[] | Prisma.SongUncheckedCreateWithoutAlbumInput[]
  connectOrCreate?: Prisma.SongCreateOrConnectWithoutAlbumInput | Prisma.SongCreateOrConnectWithoutAlbumInput[]
  upsert?: Prisma.SongUpsertWithWhereUniqueWithoutAlbumInput | Prisma.SongUpsertWithWhereUniqueWithoutAlbumInput[]
  createMany?: Prisma.SongCreateManyAlbumInputEnvelope
  set?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  disconnect?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  delete?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  connect?: Prisma.SongWhereUniqueInput | Prisma.SongWhereUniqueInput[]
  update?: Prisma.SongUpdateWithWhereUniqueWithoutAlbumInput | Prisma.SongUpdateWithWhereUniqueWithoutAlbumInput[]
  updateMany?: Prisma.SongUpdateManyWithWhereWithoutAlbumInput | Prisma.SongUpdateManyWithWhereWithoutAlbumInput[]
  deleteMany?: Prisma.SongScalarWhereInput | Prisma.SongScalarWhereInput[]
}

export type SongCreateWithoutArtistsInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  image: string
  plainLyrics: string
  syncedLyrics: string
  playlistSongs?: Prisma.PlaylistSongCreateNestedManyWithoutSongInput
  album?: Prisma.AlbumCreateNestedOneWithoutSongsInput
  queueSongs?: Prisma.QueueSongCreateNestedManyWithoutSongInput
}

export type SongUncheckedCreateWithoutArtistsInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  albumId?: string | null
  image: string
  plainLyrics: string
  syncedLyrics: string
  playlistSongs?: Prisma.PlaylistSongUncheckedCreateNestedManyWithoutSongInput
  queueSongs?: Prisma.QueueSongUncheckedCreateNestedManyWithoutSongInput
}

export type SongCreateOrConnectWithoutArtistsInput = {
  where: Prisma.SongWhereUniqueInput
  create: Prisma.XOR<Prisma.SongCreateWithoutArtistsInput, Prisma.SongUncheckedCreateWithoutArtistsInput>
}

export type SongUpsertWithoutArtistsInput = {
  update: Prisma.XOR<Prisma.SongUpdateWithoutArtistsInput, Prisma.SongUncheckedUpdateWithoutArtistsInput>
  create: Prisma.XOR<Prisma.SongCreateWithoutArtistsInput, Prisma.SongUncheckedCreateWithoutArtistsInput>
  where?: Prisma.SongWhereInput
}

export type SongUpdateToOneWithWhereWithoutArtistsInput = {
  where?: Prisma.SongWhereInput
  data: Prisma.XOR<Prisma.SongUpdateWithoutArtistsInput, Prisma.SongUncheckedUpdateWithoutArtistsInput>
}

export type SongUpdateWithoutArtistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  playlistSongs?: Prisma.PlaylistSongUpdateManyWithoutSongNestedInput
  album?: Prisma.AlbumUpdateOneWithoutSongsNestedInput
  queueSongs?: Prisma.QueueSongUpdateManyWithoutSongNestedInput
}

export type SongUncheckedUpdateWithoutArtistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  albumId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  playlistSongs?: Prisma.PlaylistSongUncheckedUpdateManyWithoutSongNestedInput
  queueSongs?: Prisma.QueueSongUncheckedUpdateManyWithoutSongNestedInput
}

export type SongCreateWithoutPlaylistSongsInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistCreateNestedManyWithoutSongInput
  album?: Prisma.AlbumCreateNestedOneWithoutSongsInput
  queueSongs?: Prisma.QueueSongCreateNestedManyWithoutSongInput
}

export type SongUncheckedCreateWithoutPlaylistSongsInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  albumId?: string | null
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistUncheckedCreateNestedManyWithoutSongInput
  queueSongs?: Prisma.QueueSongUncheckedCreateNestedManyWithoutSongInput
}

export type SongCreateOrConnectWithoutPlaylistSongsInput = {
  where: Prisma.SongWhereUniqueInput
  create: Prisma.XOR<Prisma.SongCreateWithoutPlaylistSongsInput, Prisma.SongUncheckedCreateWithoutPlaylistSongsInput>
}

export type SongUpsertWithoutPlaylistSongsInput = {
  update: Prisma.XOR<Prisma.SongUpdateWithoutPlaylistSongsInput, Prisma.SongUncheckedUpdateWithoutPlaylistSongsInput>
  create: Prisma.XOR<Prisma.SongCreateWithoutPlaylistSongsInput, Prisma.SongUncheckedCreateWithoutPlaylistSongsInput>
  where?: Prisma.SongWhereInput
}

export type SongUpdateToOneWithWhereWithoutPlaylistSongsInput = {
  where?: Prisma.SongWhereInput
  data: Prisma.XOR<Prisma.SongUpdateWithoutPlaylistSongsInput, Prisma.SongUncheckedUpdateWithoutPlaylistSongsInput>
}

export type SongUpdateWithoutPlaylistSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUpdateManyWithoutSongNestedInput
  album?: Prisma.AlbumUpdateOneWithoutSongsNestedInput
  queueSongs?: Prisma.QueueSongUpdateManyWithoutSongNestedInput
}

export type SongUncheckedUpdateWithoutPlaylistSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  albumId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUncheckedUpdateManyWithoutSongNestedInput
  queueSongs?: Prisma.QueueSongUncheckedUpdateManyWithoutSongNestedInput
}

export type SongCreateWithoutQueueSongsInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistCreateNestedManyWithoutSongInput
  playlistSongs?: Prisma.PlaylistSongCreateNestedManyWithoutSongInput
  album?: Prisma.AlbumCreateNestedOneWithoutSongsInput
}

export type SongUncheckedCreateWithoutQueueSongsInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  albumId?: string | null
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistUncheckedCreateNestedManyWithoutSongInput
  playlistSongs?: Prisma.PlaylistSongUncheckedCreateNestedManyWithoutSongInput
}

export type SongCreateOrConnectWithoutQueueSongsInput = {
  where: Prisma.SongWhereUniqueInput
  create: Prisma.XOR<Prisma.SongCreateWithoutQueueSongsInput, Prisma.SongUncheckedCreateWithoutQueueSongsInput>
}

export type SongUpsertWithoutQueueSongsInput = {
  update: Prisma.XOR<Prisma.SongUpdateWithoutQueueSongsInput, Prisma.SongUncheckedUpdateWithoutQueueSongsInput>
  create: Prisma.XOR<Prisma.SongCreateWithoutQueueSongsInput, Prisma.SongUncheckedCreateWithoutQueueSongsInput>
  where?: Prisma.SongWhereInput
}

export type SongUpdateToOneWithWhereWithoutQueueSongsInput = {
  where?: Prisma.SongWhereInput
  data: Prisma.XOR<Prisma.SongUpdateWithoutQueueSongsInput, Prisma.SongUncheckedUpdateWithoutQueueSongsInput>
}

export type SongUpdateWithoutQueueSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUpdateManyWithoutSongNestedInput
  playlistSongs?: Prisma.PlaylistSongUpdateManyWithoutSongNestedInput
  album?: Prisma.AlbumUpdateOneWithoutSongsNestedInput
}

export type SongUncheckedUpdateWithoutQueueSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  albumId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUncheckedUpdateManyWithoutSongNestedInput
  playlistSongs?: Prisma.PlaylistSongUncheckedUpdateManyWithoutSongNestedInput
}

export type SongCreateWithoutAlbumInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistCreateNestedManyWithoutSongInput
  playlistSongs?: Prisma.PlaylistSongCreateNestedManyWithoutSongInput
  queueSongs?: Prisma.QueueSongCreateNestedManyWithoutSongInput
}

export type SongUncheckedCreateWithoutAlbumInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  image: string
  plainLyrics: string
  syncedLyrics: string
  artists?: Prisma.SongArtistUncheckedCreateNestedManyWithoutSongInput
  playlistSongs?: Prisma.PlaylistSongUncheckedCreateNestedManyWithoutSongInput
  queueSongs?: Prisma.QueueSongUncheckedCreateNestedManyWithoutSongInput
}

export type SongCreateOrConnectWithoutAlbumInput = {
  where: Prisma.SongWhereUniqueInput
  create: Prisma.XOR<Prisma.SongCreateWithoutAlbumInput, Prisma.SongUncheckedCreateWithoutAlbumInput>
}

export type SongCreateManyAlbumInputEnvelope = {
  data: Prisma.SongCreateManyAlbumInput | Prisma.SongCreateManyAlbumInput[]
  skipDuplicates?: boolean
}

export type SongUpsertWithWhereUniqueWithoutAlbumInput = {
  where: Prisma.SongWhereUniqueInput
  update: Prisma.XOR<Prisma.SongUpdateWithoutAlbumInput, Prisma.SongUncheckedUpdateWithoutAlbumInput>
  create: Prisma.XOR<Prisma.SongCreateWithoutAlbumInput, Prisma.SongUncheckedCreateWithoutAlbumInput>
}

export type SongUpdateWithWhereUniqueWithoutAlbumInput = {
  where: Prisma.SongWhereUniqueInput
  data: Prisma.XOR<Prisma.SongUpdateWithoutAlbumInput, Prisma.SongUncheckedUpdateWithoutAlbumInput>
}

export type SongUpdateManyWithWhereWithoutAlbumInput = {
  where: Prisma.SongScalarWhereInput
  data: Prisma.XOR<Prisma.SongUpdateManyMutationInput, Prisma.SongUncheckedUpdateManyWithoutAlbumInput>
}

export type SongScalarWhereInput = {
  AND?: Prisma.SongScalarWhereInput | Prisma.SongScalarWhereInput[]
  OR?: Prisma.SongScalarWhereInput[]
  NOT?: Prisma.SongScalarWhereInput | Prisma.SongScalarWhereInput[]
  id?: Prisma.StringFilter<"Song"> | string
  title?: Prisma.StringFilter<"Song"> | string
  fileName?: Prisma.StringFilter<"Song"> | string
  duration?: Prisma.IntFilter<"Song"> | number
  albumId?: Prisma.StringNullableFilter<"Song"> | string | null
  image?: Prisma.StringFilter<"Song"> | string
  plainLyrics?: Prisma.StringFilter<"Song"> | string
  syncedLyrics?: Prisma.StringFilter<"Song"> | string
}

export type SongCreateManyAlbumInput = {
  id?: string
  title: string
  fileName: string
  duration: number
  image: string
  plainLyrics: string
  syncedLyrics: string
}

export type SongUpdateWithoutAlbumInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUpdateManyWithoutSongNestedInput
  playlistSongs?: Prisma.PlaylistSongUpdateManyWithoutSongNestedInput
  queueSongs?: Prisma.QueueSongUpdateManyWithoutSongNestedInput
}

export type SongUncheckedUpdateWithoutAlbumInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  artists?: Prisma.SongArtistUncheckedUpdateManyWithoutSongNestedInput
  playlistSongs?: Prisma.PlaylistSongUncheckedUpdateManyWithoutSongNestedInput
  queueSongs?: Prisma.QueueSongUncheckedUpdateManyWithoutSongNestedInput
}

export type SongUncheckedUpdateManyWithoutAlbumInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.StringFieldUpdateOperationsInput | string
  plainLyrics?: Prisma.StringFieldUpdateOperationsInput | string
  syncedLyrics?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type SongCountOutputType
 */

export type SongCountOutputType = {
  artists: number
  playlistSongs: number
  queueSongs: number
}

export type SongCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  artists?: boolean | SongCountOutputTypeCountArtistsArgs
  playlistSongs?: boolean | SongCountOutputTypeCountPlaylistSongsArgs
  queueSongs?: boolean | SongCountOutputTypeCountQueueSongsArgs
}

/**
 * SongCountOutputType without action
 */
export type SongCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongCountOutputType
   */
  select?: Prisma.SongCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SongCountOutputType without action
 */
export type SongCountOutputTypeCountArtistsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SongArtistWhereInput
}

/**
 * SongCountOutputType without action
 */
export type SongCountOutputTypeCountPlaylistSongsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaylistSongWhereInput
}

/**
 * SongCountOutputType without action
 */
export type SongCountOutputTypeCountQueueSongsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QueueSongWhereInput
}


export type SongSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  fileName?: boolean
  duration?: boolean
  albumId?: boolean
  image?: boolean
  plainLyrics?: boolean
  syncedLyrics?: boolean
  artists?: boolean | Prisma.Song$artistsArgs<ExtArgs>
  playlistSongs?: boolean | Prisma.Song$playlistSongsArgs<ExtArgs>
  album?: boolean | Prisma.Song$albumArgs<ExtArgs>
  queueSongs?: boolean | Prisma.Song$queueSongsArgs<ExtArgs>
  _count?: boolean | Prisma.SongCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["song"]>

export type SongSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  fileName?: boolean
  duration?: boolean
  albumId?: boolean
  image?: boolean
  plainLyrics?: boolean
  syncedLyrics?: boolean
  album?: boolean | Prisma.Song$albumArgs<ExtArgs>
}, ExtArgs["result"]["song"]>

export type SongSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  fileName?: boolean
  duration?: boolean
  albumId?: boolean
  image?: boolean
  plainLyrics?: boolean
  syncedLyrics?: boolean
  album?: boolean | Prisma.Song$albumArgs<ExtArgs>
}, ExtArgs["result"]["song"]>

export type SongSelectScalar = {
  id?: boolean
  title?: boolean
  fileName?: boolean
  duration?: boolean
  albumId?: boolean
  image?: boolean
  plainLyrics?: boolean
  syncedLyrics?: boolean
}

export type SongOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "fileName" | "duration" | "albumId" | "image" | "plainLyrics" | "syncedLyrics", ExtArgs["result"]["song"]>
export type SongInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  artists?: boolean | Prisma.Song$artistsArgs<ExtArgs>
  playlistSongs?: boolean | Prisma.Song$playlistSongsArgs<ExtArgs>
  album?: boolean | Prisma.Song$albumArgs<ExtArgs>
  queueSongs?: boolean | Prisma.Song$queueSongsArgs<ExtArgs>
  _count?: boolean | Prisma.SongCountOutputTypeDefaultArgs<ExtArgs>
}
export type SongIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  album?: boolean | Prisma.Song$albumArgs<ExtArgs>
}
export type SongIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  album?: boolean | Prisma.Song$albumArgs<ExtArgs>
}

export type $SongPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Song"
  objects: {
    artists: Prisma.$SongArtistPayload<ExtArgs>[]
    playlistSongs: Prisma.$PlaylistSongPayload<ExtArgs>[]
    album: Prisma.$AlbumPayload<ExtArgs> | null
    queueSongs: Prisma.$QueueSongPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    fileName: string
    duration: number
    albumId: string | null
    image: string
    plainLyrics: string
    syncedLyrics: string
  }, ExtArgs["result"]["song"]>
  composites: {}
}

export type SongGetPayload<S extends boolean | null | undefined | SongDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SongPayload, S>

export type SongCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SongFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SongCountAggregateInputType | true
  }

export interface SongDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Song'], meta: { name: 'Song' } }
  /**
   * Find zero or one Song that matches the filter.
   * @param {SongFindUniqueArgs} args - Arguments to find a Song
   * @example
   * // Get one Song
   * const song = await prisma.song.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SongFindUniqueArgs>(args: Prisma.SelectSubset<T, SongFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Song that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SongFindUniqueOrThrowArgs} args - Arguments to find a Song
   * @example
   * // Get one Song
   * const song = await prisma.song.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SongFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SongFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Song that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongFindFirstArgs} args - Arguments to find a Song
   * @example
   * // Get one Song
   * const song = await prisma.song.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SongFindFirstArgs>(args?: Prisma.SelectSubset<T, SongFindFirstArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Song that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongFindFirstOrThrowArgs} args - Arguments to find a Song
   * @example
   * // Get one Song
   * const song = await prisma.song.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SongFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SongFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Songs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Songs
   * const songs = await prisma.song.findMany()
   * 
   * // Get first 10 Songs
   * const songs = await prisma.song.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const songWithIdOnly = await prisma.song.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SongFindManyArgs>(args?: Prisma.SelectSubset<T, SongFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Song.
   * @param {SongCreateArgs} args - Arguments to create a Song.
   * @example
   * // Create one Song
   * const Song = await prisma.song.create({
   *   data: {
   *     // ... data to create a Song
   *   }
   * })
   * 
   */
  create<T extends SongCreateArgs>(args: Prisma.SelectSubset<T, SongCreateArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Songs.
   * @param {SongCreateManyArgs} args - Arguments to create many Songs.
   * @example
   * // Create many Songs
   * const song = await prisma.song.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SongCreateManyArgs>(args?: Prisma.SelectSubset<T, SongCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Songs and returns the data saved in the database.
   * @param {SongCreateManyAndReturnArgs} args - Arguments to create many Songs.
   * @example
   * // Create many Songs
   * const song = await prisma.song.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Songs and only return the `id`
   * const songWithIdOnly = await prisma.song.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SongCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SongCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Song.
   * @param {SongDeleteArgs} args - Arguments to delete one Song.
   * @example
   * // Delete one Song
   * const Song = await prisma.song.delete({
   *   where: {
   *     // ... filter to delete one Song
   *   }
   * })
   * 
   */
  delete<T extends SongDeleteArgs>(args: Prisma.SelectSubset<T, SongDeleteArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Song.
   * @param {SongUpdateArgs} args - Arguments to update one Song.
   * @example
   * // Update one Song
   * const song = await prisma.song.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SongUpdateArgs>(args: Prisma.SelectSubset<T, SongUpdateArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Songs.
   * @param {SongDeleteManyArgs} args - Arguments to filter Songs to delete.
   * @example
   * // Delete a few Songs
   * const { count } = await prisma.song.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SongDeleteManyArgs>(args?: Prisma.SelectSubset<T, SongDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Songs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Songs
   * const song = await prisma.song.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SongUpdateManyArgs>(args: Prisma.SelectSubset<T, SongUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Songs and returns the data updated in the database.
   * @param {SongUpdateManyAndReturnArgs} args - Arguments to update many Songs.
   * @example
   * // Update many Songs
   * const song = await prisma.song.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Songs and only return the `id`
   * const songWithIdOnly = await prisma.song.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SongUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SongUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Song.
   * @param {SongUpsertArgs} args - Arguments to update or create a Song.
   * @example
   * // Update or create a Song
   * const song = await prisma.song.upsert({
   *   create: {
   *     // ... data to create a Song
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Song we want to update
   *   }
   * })
   */
  upsert<T extends SongUpsertArgs>(args: Prisma.SelectSubset<T, SongUpsertArgs<ExtArgs>>): Prisma.Prisma__SongClient<runtime.Types.Result.GetResult<Prisma.$SongPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Songs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongCountArgs} args - Arguments to filter Songs to count.
   * @example
   * // Count the number of Songs
   * const count = await prisma.song.count({
   *   where: {
   *     // ... the filter for the Songs we want to count
   *   }
   * })
  **/
  count<T extends SongCountArgs>(
    args?: Prisma.Subset<T, SongCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SongCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Song.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SongAggregateArgs>(args: Prisma.Subset<T, SongAggregateArgs>): Prisma.PrismaPromise<GetSongAggregateType<T>>

  /**
   * Group by Song.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SongGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SongGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SongGroupByArgs['orderBy'] }
      : { orderBy?: SongGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SongGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSongGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Song model
 */
readonly fields: SongFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Song.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SongClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  artists<T extends Prisma.Song$artistsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Song$artistsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SongArtistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  playlistSongs<T extends Prisma.Song$playlistSongsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Song$playlistSongsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaylistSongPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  album<T extends Prisma.Song$albumArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Song$albumArgs<ExtArgs>>): Prisma.Prisma__AlbumClient<runtime.Types.Result.GetResult<Prisma.$AlbumPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  queueSongs<T extends Prisma.Song$queueSongsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Song$queueSongsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueSongPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Song model
 */
export interface SongFieldRefs {
  readonly id: Prisma.FieldRef<"Song", 'String'>
  readonly title: Prisma.FieldRef<"Song", 'String'>
  readonly fileName: Prisma.FieldRef<"Song", 'String'>
  readonly duration: Prisma.FieldRef<"Song", 'Int'>
  readonly albumId: Prisma.FieldRef<"Song", 'String'>
  readonly image: Prisma.FieldRef<"Song", 'String'>
  readonly plainLyrics: Prisma.FieldRef<"Song", 'String'>
  readonly syncedLyrics: Prisma.FieldRef<"Song", 'String'>
}
    

// Custom InputTypes
/**
 * Song findUnique
 */
export type SongFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * Filter, which Song to fetch.
   */
  where: Prisma.SongWhereUniqueInput
}

/**
 * Song findUniqueOrThrow
 */
export type SongFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * Filter, which Song to fetch.
   */
  where: Prisma.SongWhereUniqueInput
}

/**
 * Song findFirst
 */
export type SongFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * Filter, which Song to fetch.
   */
  where?: Prisma.SongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Songs to fetch.
   */
  orderBy?: Prisma.SongOrderByWithRelationInput | Prisma.SongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Songs.
   */
  cursor?: Prisma.SongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Songs.
   */
  distinct?: Prisma.SongScalarFieldEnum | Prisma.SongScalarFieldEnum[]
}

/**
 * Song findFirstOrThrow
 */
export type SongFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * Filter, which Song to fetch.
   */
  where?: Prisma.SongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Songs to fetch.
   */
  orderBy?: Prisma.SongOrderByWithRelationInput | Prisma.SongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Songs.
   */
  cursor?: Prisma.SongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Songs.
   */
  distinct?: Prisma.SongScalarFieldEnum | Prisma.SongScalarFieldEnum[]
}

/**
 * Song findMany
 */
export type SongFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * Filter, which Songs to fetch.
   */
  where?: Prisma.SongWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Songs to fetch.
   */
  orderBy?: Prisma.SongOrderByWithRelationInput | Prisma.SongOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Songs.
   */
  cursor?: Prisma.SongWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Songs.
   */
  distinct?: Prisma.SongScalarFieldEnum | Prisma.SongScalarFieldEnum[]
}

/**
 * Song create
 */
export type SongCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * The data needed to create a Song.
   */
  data: Prisma.XOR<Prisma.SongCreateInput, Prisma.SongUncheckedCreateInput>
}

/**
 * Song createMany
 */
export type SongCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Songs.
   */
  data: Prisma.SongCreateManyInput | Prisma.SongCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Song createManyAndReturn
 */
export type SongCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * The data used to create many Songs.
   */
  data: Prisma.SongCreateManyInput | Prisma.SongCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Song update
 */
export type SongUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * The data needed to update a Song.
   */
  data: Prisma.XOR<Prisma.SongUpdateInput, Prisma.SongUncheckedUpdateInput>
  /**
   * Choose, which Song to update.
   */
  where: Prisma.SongWhereUniqueInput
}

/**
 * Song updateMany
 */
export type SongUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Songs.
   */
  data: Prisma.XOR<Prisma.SongUpdateManyMutationInput, Prisma.SongUncheckedUpdateManyInput>
  /**
   * Filter which Songs to update
   */
  where?: Prisma.SongWhereInput
  /**
   * Limit how many Songs to update.
   */
  limit?: number
}

/**
 * Song updateManyAndReturn
 */
export type SongUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * The data used to update Songs.
   */
  data: Prisma.XOR<Prisma.SongUpdateManyMutationInput, Prisma.SongUncheckedUpdateManyInput>
  /**
   * Filter which Songs to update
   */
  where?: Prisma.SongWhereInput
  /**
   * Limit how many Songs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Song upsert
 */
export type SongUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * The filter to search for the Song to update in case it exists.
   */
  where: Prisma.SongWhereUniqueInput
  /**
   * In case the Song found by the `where` argument doesn't exist, create a new Song with this data.
   */
  create: Prisma.XOR<Prisma.SongCreateInput, Prisma.SongUncheckedCreateInput>
  /**
   * In case the Song was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SongUpdateInput, Prisma.SongUncheckedUpdateInput>
}

/**
 * Song delete
 */
export type SongDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
  /**
   * Filter which Song to delete.
   */
  where: Prisma.SongWhereUniqueInput
}

/**
 * Song deleteMany
 */
export type SongDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Songs to delete
   */
  where?: Prisma.SongWhereInput
  /**
   * Limit how many Songs to delete.
   */
  limit?: number
}

/**
 * Song.artists
 */
export type Song$artistsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SongArtist
   */
  select?: Prisma.SongArtistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SongArtist
   */
  omit?: Prisma.SongArtistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongArtistInclude<ExtArgs> | null
  where?: Prisma.SongArtistWhereInput
  orderBy?: Prisma.SongArtistOrderByWithRelationInput | Prisma.SongArtistOrderByWithRelationInput[]
  cursor?: Prisma.SongArtistWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SongArtistScalarFieldEnum | Prisma.SongArtistScalarFieldEnum[]
}

/**
 * Song.playlistSongs
 */
export type Song$playlistSongsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaylistSong
   */
  select?: Prisma.PlaylistSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaylistSong
   */
  omit?: Prisma.PlaylistSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaylistSongInclude<ExtArgs> | null
  where?: Prisma.PlaylistSongWhereInput
  orderBy?: Prisma.PlaylistSongOrderByWithRelationInput | Prisma.PlaylistSongOrderByWithRelationInput[]
  cursor?: Prisma.PlaylistSongWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PlaylistSongScalarFieldEnum | Prisma.PlaylistSongScalarFieldEnum[]
}

/**
 * Song.album
 */
export type Song$albumArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Album
   */
  select?: Prisma.AlbumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Album
   */
  omit?: Prisma.AlbumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AlbumInclude<ExtArgs> | null
  where?: Prisma.AlbumWhereInput
}

/**
 * Song.queueSongs
 */
export type Song$queueSongsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueSong
   */
  select?: Prisma.QueueSongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueSong
   */
  omit?: Prisma.QueueSongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QueueSongInclude<ExtArgs> | null
  where?: Prisma.QueueSongWhereInput
  orderBy?: Prisma.QueueSongOrderByWithRelationInput | Prisma.QueueSongOrderByWithRelationInput[]
  cursor?: Prisma.QueueSongWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QueueSongScalarFieldEnum | Prisma.QueueSongScalarFieldEnum[]
}

/**
 * Song without action
 */
export type SongDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Song
   */
  select?: Prisma.SongSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Song
   */
  omit?: Prisma.SongOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SongInclude<ExtArgs> | null
}
