
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  SongArtist: 'SongArtist',
  Playlist: 'Playlist',
  PlaylistSong: 'PlaylistSong',
  Queue: 'Queue',
  QueueSong: 'QueueSong',
  Song: 'Song',
  Artist: 'Artist',
  Album: 'Album'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  clerkId: 'clerkId',
  username: 'username',
  email: 'email',
  image: 'image'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SongArtistScalarFieldEnum = {
  songId: 'songId',
  artistId: 'artistId'
} as const

export type SongArtistScalarFieldEnum = (typeof SongArtistScalarFieldEnum)[keyof typeof SongArtistScalarFieldEnum]


export const PlaylistScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  isPublic: 'isPublic'
} as const

export type PlaylistScalarFieldEnum = (typeof PlaylistScalarFieldEnum)[keyof typeof PlaylistScalarFieldEnum]


export const PlaylistSongScalarFieldEnum = {
  id: 'id',
  playlistId: 'playlistId',
  songId: 'songId',
  position: 'position'
} as const

export type PlaylistSongScalarFieldEnum = (typeof PlaylistSongScalarFieldEnum)[keyof typeof PlaylistSongScalarFieldEnum]


export const QueueScalarFieldEnum = {
  id: 'id',
  userId: 'userId'
} as const

export type QueueScalarFieldEnum = (typeof QueueScalarFieldEnum)[keyof typeof QueueScalarFieldEnum]


export const QueueSongScalarFieldEnum = {
  id: 'id',
  queueId: 'queueId',
  songId: 'songId',
  position: 'position'
} as const

export type QueueSongScalarFieldEnum = (typeof QueueSongScalarFieldEnum)[keyof typeof QueueSongScalarFieldEnum]


export const SongScalarFieldEnum = {
  id: 'id',
  title: 'title',
  fileName: 'fileName',
  duration: 'duration',
  albumId: 'albumId',
  image: 'image',
  plainLyrics: 'plainLyrics',
  syncedLyrics: 'syncedLyrics'
} as const

export type SongScalarFieldEnum = (typeof SongScalarFieldEnum)[keyof typeof SongScalarFieldEnum]


export const ArtistScalarFieldEnum = {
  id: 'id',
  name: 'name',
  bio: 'bio',
  image: 'image'
} as const

export type ArtistScalarFieldEnum = (typeof ArtistScalarFieldEnum)[keyof typeof ArtistScalarFieldEnum]


export const AlbumScalarFieldEnum = {
  id: 'id',
  name: 'name',
  artistId: 'artistId',
  image: 'image',
  songId: 'songId'
} as const

export type AlbumScalarFieldEnum = (typeof AlbumScalarFieldEnum)[keyof typeof AlbumScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

